using UnityEngine;
namespace Wuxia {
 public class EffectPool {
  class Particle {public SpriteView view;public float born,life,x,y,vx,vy,w,h,angle,spin,offsetX,offsetY,grow;public Vector3 baseScale;public bool gravity;public Color color;public string animation;public int frames;public Actor follow;}
  class Stroke {public LineRenderer line;public float born,life;public Color color;}
  readonly Particle[] particles=new Particle[128];readonly Stroke[] strokes=new Stroke[32];readonly ArtLibrary art;readonly Material material;int pi,li;
  public EffectPool(ArtLibrary library,Transform parent){art=library;material=new Material(Shader.Find("Sprites/Default"));for(int i=0;i<particles.Length;i++){particles[i]=new Particle{view=new SpriteView(art,parent,"复用特效 "+i,45)};particles[i].view.Visible(false);}for(int i=0;i<strokes.Length;i++){var g=new GameObject("复用光线 "+i);g.transform.SetParent(parent);var line=g.AddComponent<LineRenderer>();line.sharedMaterial=material;line.useWorldSpace=true;line.sortingOrder=44;line.numCapVertices=2;line.enabled=false;strokes[i]=new Stroke{line=line};}}
  public void Sprite(string sheet,string frame,float x,float y,float w,float h,float born,float life,Color color,float vx=0,float vy=0,bool gravity=false,float angle=0,bool additive=false,float grow=1){var p=particles[pi++%particles.Length];p.grow=grow;p.view.Additive(additive);p.born=born;p.life=life;p.x=x;p.y=y;p.vx=vx;p.vy=vy;p.gravity=gravity;p.w=w;p.h=h;p.color=color;p.angle=angle;p.animation=null;p.follow=null;p.frames=0;p.spin=gravity?UnityEngine.Random.Range(-5f,5f):0;p.view.renderer.sortingOrder=45;p.view.SnapNext();p.view.Image(sheet,frame,x,y,w,h,angle);p.baseScale=p.view.root.transform.localScale;p.view.Color(color);p.view.Visible(true);}
  public void Animated(string sheet,int frames,float x,float y,float w,float h,float now,float life,Color color,float angle=0,Actor follow=null,int order=45){Sprite(sheet,"0",x,y,w,h,now,life,color,angle:angle);var p=particles[(pi-1)%particles.Length];p.animation=sheet;p.frames=frames;p.follow=follow;p.offsetX=follow!=null?x-follow.X:0;p.offsetY=follow!=null?y-follow.CenterY:0;p.view.renderer.sortingOrder=order;}
  public void Burst(float x,float y,int count,Color color,float now){if(count<=0)return;float size=28+Mathf.Min(count,40)*1.35f;Animated("pixelHit",6,x,y,size,size*68/55,now,.26f,Color.Lerp(Color.white,color,.2f));}
  public void FollowActors(){foreach(var p in particles)if(p.follow!=null&&p.view.renderer.enabled){if(p.follow.hp<=0||!p.follow.root){p.view.Visible(false);p.follow=null;continue;}p.x=p.follow.X+p.offsetX;p.y=p.follow.CenterY+p.offsetY;p.view.Position(PixelWorld.Position(p.x,p.y),Quaternion.Euler(0,0,-p.angle*Mathf.Rad2Deg));}}
  public void Line(Vector2[] points,float width,Color color,float now,float life){var s=strokes[li++%strokes.Length];s.born=now;s.life=life;s.color=color;s.line.positionCount=points.Length;for(int i=0;i<points.Length;i++)s.line.SetPosition(i,PixelWorld.Position(points[i].x,points[i].y));s.line.startWidth=s.line.endWidth=width/100;s.line.startColor=s.line.endColor=color;s.line.enabled=true;}
  public void Ring(float x,float y,float w,float h,Color color,float now,float life=.12f,float width=2){var points=new Vector2[33];for(int i=0;i<points.Length;i++){float a=i*Mathf.PI*2/32;points[i]=new Vector2(x+Mathf.Cos(a)*w*.5f,y+Mathf.Sin(a)*h*.5f);}Line(points,width,color,now,life);}
  public void Tick(float now,float dt){foreach(var p in particles){if(!p.view.renderer.enabled)continue;float t=(now-p.born)/p.life;if(t>=1){p.view.Visible(false);continue;}p.x+=p.vx*dt;p.y+=p.vy*dt;if(p.gravity)p.vy+=700*dt;p.angle+=p.spin*dt;if(p.animation!=null)p.view.Image(p.animation,Mathf.Min(p.frames-1,Mathf.FloorToInt(t*p.frames)).ToString(),p.x,p.y,p.w,p.h,p.angle);else p.view.Position(PixelWorld.Position(p.x,p.y),Quaternion.Euler(0,0,-p.angle*Mathf.Rad2Deg));if(p.animation==null&&p.grow!=1)p.view.root.transform.localScale=p.baseScale*Mathf.Lerp(1,p.grow,t);var c=p.color;c.a*=p.animation=="pixelFrost"?Mathf.Min(1,Mathf.Min((now-p.born)/.12f,(p.life-now+p.born)/.22f))*.8f:p.animation=="pixelHit"?Mathf.Clamp01((1-t)/.65f):1-t;p.view.Color(c);}foreach(var s in strokes){if(!s.line.enabled)continue;float t=(now-s.born)/s.life;if(t>=1){s.line.enabled=false;continue;}var c=s.color;c.a*=1-t;s.line.startColor=s.line.endColor=c;}}
  public void Clear(){foreach(var p in particles){p.view.Visible(false);p.follow=null;}foreach(var s in strokes)s.line.enabled=false;}
  public int ActiveCount {get{int n=0;foreach(var p in particles)if(p.view.renderer.enabled)n++;foreach(var s in strokes)if(s.line.enabled)n++;return n;}}
  public bool HasActiveSheet(string sheet){foreach(var p in particles)if(p.view.renderer.enabled&&p.view.renderer.sprite&&p.view.renderer.sprite.name.StartsWith(sheet+":"))return true;return false;}
  public void Dispose()=>NativeObject.Remove(material);
 }
}
