using System;using System.Collections.Generic;using UnityEngine;using UnityEngine.UI;using UnityEngine.EventSystems;
namespace Wuxia {
 public class NativeUI:MonoBehaviour {
  WuxiaGame game;Canvas canvas;RectTransform root,modal,hud;Font font;Text hpText,placeText,prompt,notice,bossName,bossWarning,kText,lText;Image hpFill,kFill,lFill,bossFill;RectTransform bossPanel,warningPlate;Image novaBar;Text novaCountdown;Button home;readonly List<Image> learned=new List<Image>();readonly List<Button> cards=new List<Button>();readonly List<RectTransform> talentTiles=new List<RectTransform>();readonly List<Text> talentLevels=new List<Text>();readonly List<GameObject> selectedMarks=new List<GameObject>();readonly List<CanvasGroup> cardGroups=new List<CanvasGroup>();readonly List<CultivationFrame> cardFrames=new List<CultivationFrame>();Text cardPreview,cardHealth,confirmText,formationFeedback;float feedbackUntil,feedbackAt,feedbackX,feedbackY,feedbackPunch;Button confirm;float animAt;Image unlockPortrait;Text[] worldHints=new Text[4];
  readonly Color ink=new Color(.13f,.22f,.23f),gold=new Color(.86f,.73f,.47f),pale=new Color(.94f,.87f,.7f),teal=new Color(.43f,.8f,.74f);public bool HasModal=>modal!=null&&modal.gameObject.activeSelf;
  public void Initialize(WuxiaGame value){game=value;font=Resources.Load<Font>("Fonts/NotoSerifCJKsc-Regular");if(!font)font=Resources.GetBuiltinResource<Font>("LegacyRuntime.ttf");var go=new GameObject("原生卷轴界面",typeof(RectTransform));go.transform.SetParent(transform);canvas=go.AddComponent<Canvas>();canvas.renderMode=RenderMode.ScreenSpaceOverlay;canvas.sortingOrder=100;var scaler=go.AddComponent<CanvasScaler>();scaler.uiScaleMode=CanvasScaler.ScaleMode.ScaleWithScreenSize;scaler.referenceResolution=new Vector2(1280,720);scaler.screenMatchMode=CanvasScaler.ScreenMatchMode.Expand;go.AddComponent<GraphicRaycaster>();root=go.GetComponent<RectTransform>();if(!FindFirstObjectByType<EventSystem>()){var es=new GameObject("鼠标键盘交互",typeof(EventSystem),typeof(StandaloneInputModule));es.transform.SetParent(transform);}MakeHUD();FitScreen();}
  RectTransform Rect(string name,Transform parent,float x,float y,float w,float h){var g=new GameObject(name,typeof(RectTransform));var r=g.GetComponent<RectTransform>();r.SetParent(parent,false);r.anchorMin=r.anchorMax=new Vector2(0,1);r.pivot=new Vector2(0,1);r.anchoredPosition=new Vector2(x,-y);r.sizeDelta=new Vector2(w,h);return r;}
  Image Box(Transform parent,float x,float y,float w,float h,Color color,string name="装饰"){var r=Rect(name,parent,x,y,w,h);var image=r.gameObject.AddComponent<Image>();image.color=color;image.raycastTarget=false;return image;}
  Image Art(Transform parent,string sheet,string frame,float x,float y,float w,float h,Color? color=null){var image=Box(parent,x,y,w,h,color??Color.white,sheet);image.sprite=game.art.Sprite(sheet,frame);image.preserveAspect=true;return image;}
  Text Label(Transform parent,string text,float x,float y,float w,float h,int size,Color color,TextAnchor anchor=TextAnchor.MiddleLeft){var r=Rect(text,parent,x,y,w,h);var t=r.gameObject.AddComponent<Text>();t.font=font;t.text=text;t.fontSize=size;t.color=color;t.alignment=anchor;t.horizontalOverflow=HorizontalWrapMode.Wrap;t.verticalOverflow=VerticalWrapMode.Truncate;t.raycastTarget=false;t.resizeTextForBestFit=true;t.resizeTextMinSize=Mathf.Min(size,Mathf.Max(10,Mathf.FloorToInt(size*.75f)));t.resizeTextMaxSize=size;return t;}
  RectTransform Scroll(Transform parent,float x,float y,float w,float h,bool dark=false,int style=0){
   if(dark&&style==0)style=1;var r=Rect("武侠卷轴",parent,x,y,w,h);Color paper=style==2?new Color(.93f,.9f,.8f):new Color(.882f,.827f,.69f),edge=style==1?new Color(.27f,.4f,.35f):new Color(.6f,.47f,.31f);
   Box(r,5,5,w-4,h,new Color(.02f,.05f,.04f,.25f));Box(r,4,0,w-8,h,paper);
   var grain=Box(r,4,0,w-8,h,new Color(1,1,1,.075f));grain.sprite=game.art.Sprite("parchment");grain.preserveAspect=false;
   Box(r,11,7,w-22,1,edge);Box(r,11,h-8,w-22,1,edge);Box(r,11,7,1,h-14,edge);Box(r,w-12,7,1,h-14,edge);
   if(style==0){for(int yy=18;yy<h-12;yy+=17)Box(r,15,yy,w-30,1,new Color(.5f,.4f,.25f,.055f));for(int i=0;i<2;i++){float xx=i==0?0:w-8;Box(r,xx,-3,8,h+6,new Color(.34f,.29f,.22f));Box(r,xx-1,-1,10,4,gold);Box(r,xx-1,h-3,10,4,gold);}}
   else if(style==1){Box(r,0,0,5,h,edge);Box(r,w-5,0,5,h,edge);for(int i=0;i<2;i++){Box(r,i==0?0:w-10,0,10,5,gold);Box(r,i==0?0:w-10,h-5,10,5,gold);}}
   else {for(int i=0;i<2;i++){float xx=i==0?8:w-17;Box(r,xx,4,9,3,gold);Box(r,xx,h-7,9,3,gold);}}
   return r;
  }
  Button Button(Transform parent,string text,float x,float y,float w,float h,Action action,bool dark=true){var r=Scroll(parent,x,y,w,h,dark);r.name=text;var image=r.gameObject.AddComponent<Image>();image.color=new Color(1,1,1,0);image.raycastTarget=true;var b=r.gameObject.AddComponent<Button>();b.targetGraphic=image;var colors=b.colors;colors.normalColor=Color.white;colors.highlightedColor=new Color(1,.91f,.6f,.35f);colors.pressedColor=new Color(.6f,.9f,.85f,.5f);b.colors=colors;b.onClick.AddListener(()=>action());Label(r,text,18,1,w-36,h-2,23,ink,TextAnchor.MiddleCenter);return b;}
  Button ConfirmButton(Transform parent,float x,float y,float w,float h){var r=Rect("确认 · 进入下一步",parent,x,y,w,h);var face=Box(r,0,0,w,h,new Color(.1f,.25f,.23f),"确认按钮底色");face.raycastTarget=true;Box(r,4,4,w-8,1,gold);Box(r,4,h-5,w-8,1,gold);Box(r,4,4,1,h-8,gold);Box(r,w-5,4,1,h-8,gold);var b=r.gameObject.AddComponent<Button>();b.targetGraphic=face;var colors=b.colors;colors.normalColor=Color.white;colors.highlightedColor=new Color(.77f,1,.87f);colors.pressedColor=new Color(.57f,.82f,.69f);colors.disabledColor=new Color(.55f,.6f,.58f);b.colors=colors;b.onClick.AddListener(game.ConfirmCard);confirmText=Label(r,"确认修炼 · 进入下一波",12,1,w-24,h-2,18,new Color(1,.97f,.84f),TextAnchor.MiddleCenter);return b;}
  void NewModal(string name){if(modal){modal.gameObject.SetActive(false);NativeObject.Remove(modal.gameObject);}modal=Rect(name,root,0,0,1280,720);Box(modal,0,0,1280,720,new Color(.025f,.045f,.065f,.78f));}
  public void HideModal(){if(modal)modal.gameObject.SetActive(false);unlockPortrait=null;Refresh();}
  public void ShowMenu(){NewModal("主界面");Box(modal,0,0,1280,720,new Color(.02f,.055f,.065f,.32f));Art(modal,"menuTitle","0",280,70,720,210);Label(modal,"一剑归山 · 万念归元",440,260,400,42,23,gold,TextAnchor.MiddleCenter);Button(modal,"踏入江湖",430,330,420,63,game.ShowStory);Button(modal,"试剑 · 镇岳山门",430,413,420,63,game.StartTraining);Button(modal,"决战 · 魔灵老祖",430,496,420,63,game.StartFinal);Button(modal,"无尽试炼 · 轮回剑境",430,579,420,63,game.StartEndless);Refresh();}
  public void ShowStory(){NewModal("三幅剧情");Box(modal,0,0,1280,720,new Color(.03f,.08f,.085f,.98f));StoryPanel("一 · 山门旧梦","少年随玄衡掌门修行，守护归元山门。",60,48,570,245,"storyArt","0","storyPast","0");StoryPanel("二 · 魔念入心","掌门为求长生解封魔灵，山门一夜沦陷。",650,48,570,245,"storyArt","1","storyPast","1");var lower=Rect("三 · 白衣归山",modal,60,312,1160,270);Art(lower,"storyArt","2",0,0,1160,270).preserveAspect=false;Box(lower,0,0,1160,270,new Color(.02f,.07f,.08f,.42f));Art(lower,"hero","0",190,5,145,260);Art(lower,"masterAtlas","5",800,5,200,255);var s=Scroll(lower,350,123,448,120);Label(s,"三 · 白衣归山",25,12,398,34,24,ink);Label(s,"昔日少年已成白衣剑客。\n寻踏云剑诀，破石像，斩魔念，救回师门。",25,47,398,70,18,ink);Button(modal,"启程",480,622,320,56,game.StartStory);Refresh();}
  void StoryPanel(string title,string copy,float x,float y,float w,float h,string bg,string bgframe,string portrait,string pframe){var p=Rect(title,modal,x,y,w,h);Art(p,bg,bgframe,0,0,w,h).preserveAspect=false;Box(p,0,0,w,h,new Color(.03f,.06f,.08f,.4f));Art(p,portrait,pframe,5,7,160,220);var s=Scroll(p,165,110,w-178,121);Label(s,title,22,10,w-220,34,24,ink);Label(s,copy,22,48,w-220,65,19,ink);}
  public void ShowGuide(){NewModal("操作指引");var s=Scroll(modal,285,120,710,440);Label(s,"行走江湖",40,24,630,60,36,ink,TextAnchor.MiddleCenter);Label(s,"A / D 或 ← / →     移动\n空格     跃起（长按跳得更高）\nJ     近身挥剑       K     飞剑往返\nShift     踏云御剑       L     万剑归宗\nE     交互       Esc     暂停       M     静音",65,110,590,219,24,ink);Label(s,game.dashLearned?"身法与剑诀已掌握，先试剑，再破阵。":"藏剑石窟中可参悟踏云诀与万剑归宗。",40,350,630,40,18,ink,TextAnchor.MiddleCenter);Button(modal,"开始",450,590,380,58,game.FinishGuide);Refresh();}
  public void ShowPause(){NewModal("暂停");var s=Scroll(modal,390,175,500,260);Label(s,"停剑调息",40,28,420,68,36,ink,TextAnchor.MiddleCenter);Button(s,"继续江湖",65,117,370,54,game.Resume);Button(s,"返回主界面",65,186,370,54,game.ShowMenu);Refresh();}
  public void ShowUnlock(){NewModal("剑诀传承");Art(modal,"mountainStudy","0",0,0,1280,720).preserveAspect=false;Box(modal,0,0,1280,720,new Color(.025f,.07f,.08f,.38f));unlockPortrait=Art(modal,"hero","9",125,150,300,340);Art(modal,"blade","0",220,490,175,25).rectTransform.localRotation=Quaternion.Euler(0,0,90);var s=Scroll(modal,480,133,680,380);Label(s,"参悟 · 踏云剑诀",40,30,600,65,36,ink,TextAnchor.MiddleCenter);Label(s,"踏云诀",60,112,560,40,26,ink);Label(s,"Shift 御剑越崖，短暂避开敌人的锋芒。",60,158,560,52,22,ink);Label(s,"万剑归宗",60,228,560,40,26,ink);Label(s,"L 凝阵蓄剑，十二飞剑齐出追敌。",60,274,560,58,22,ink);Button(modal,"剑心已明 · 继续",615,566,420,62,game.FinishUnlock);animAt=Time.unscaledTime;Refresh();}
  public void ShowWon(){NewModal("结局");var s=Scroll(modal,280,150,720,380);Label(s,"归元 · 山门再明",45,35,630,65,38,ink,TextAnchor.MiddleCenter);Label(s,"魔念散去，玄衡重归清明。\n白衣剑客收剑归山，江湖仍待后人续写。",60,140,600,100,25,ink,TextAnchor.MiddleCenter);Button(s,"返回主界面",160,290,400,58,game.ShowMenu);Refresh();}
  public void ShowEndlessOver(){NewModal("试炼结束");var s=Scroll(modal,360,150,560,360);Label(s,"此番剑境 · 止步",30,24,500,65,36,ink,TextAnchor.MiddleCenter);Label(s,$"已破 {game.run.cleared} 波 · 斩敌 {game.run.kills}\n最高纪录 {game.run.best} 波",60,118,440,100,25,ink,TextAnchor.MiddleCenter);Button(s,"再入轮回",50,235,460,53,game.StartEndless);Button(s,"返回主界面",50,301,460,44,game.ShowMenu);Refresh();}
  public void ShowCards(){
   NewModal("机缘选卡");cards.Clear();selectedMarks.Clear();cardGroups.Clear();cardFrames.Clear();Box(modal,0,0,1280,720,new Color(.024f,.114f,.133f,1),"静墨选卡背景");
   string stage=game.rewardTotal>1?$"首领机缘 {game.rewardTotal-game.rewardRemaining+1} / {game.rewardTotal}":"参悟机缘";
   Label(modal,$"第 {game.run.wave} 波已破 · {stage}",180,43,920,46,32,new Color(.925f,.843f,.627f),TextAnchor.MiddleCenter);
   cardHealth=Label(modal,"",250,98,780,34,16,new Color(.65f,.74f,.69f),TextAnchor.MiddleCenter);
   for(int i=0;i<3;i++){
    var id=game.offers[i];var u=Array.Find(game.data.upgrades,v=>v.id==id);float x=167+i*330;var p=Rect("机缘 · "+id,modal,x,186,286,342);cardGroups.Add(p.gameObject.AddComponent<CanvasGroup>());
    Box(p,4,6,278,334,new Color(.015f,.04f,.04f,.36f));Box(p,4,4,278,334,i==1?new Color(.933f,.898f,.78f):new Color(.906f,.867f,.741f));var paper=Art(p,"parchment","0",0,0,286,342,new Color(1,1,1,.18f));paper.preserveAspect=false;
    var frame=p.gameObject.AddComponent<CultivationFrame>();cardFrames.Add(frame);frame.raycastTarget=true;var b=p.gameObject.AddComponent<Button>();b.targetGraphic=frame;b.transition=Selectable.Transition.None;b.onClick.AddListener(()=>game.ChooseCard(id));cards.Add(b);
    var border=new Color(.44f,.36f,.224f,.55f);Box(p,11,11,264,1,border);Box(p,11,330,264,1,border);Box(p,11,11,1,320,border);Box(p,274,11,1,320,border);
    int level=game.run.Level(id);Label(p,u.kind+(level>0&&id!="heal"?" · 进阶":""),15,26,256,28,13,new Color(.45f,.35f,.21f),TextAnchor.MiddleCenter);
    var medallion=Rect("圆形天赋纹章",p,100,65,86,86).gameObject.AddComponent<CultivationMedallion>();medallion.color=new Color(.09f,.243f,.247f);medallion.raycastTarget=false;Art(p,game.art.UpgradeSheet(id),id,113,78,60,60);
    Label(p,u.name,14,158,258,42,25,new Color(.125f,.227f,.20f),TextAnchor.MiddleCenter);
    Label(p,u.desc,23,206,240,69,15,new Color(.25f,.32f,.275f),TextAnchor.MiddleCenter);
    Label(p,id=="heal"?"调息 · 恢复气血":$"修炼 {level} → {level+1} 重",15,291,256,30,13,new Color(.525f,.384f,.188f),TextAnchor.MiddleCenter);
   }
   cardPreview=Label(modal,"",180,564,920,40,17,new Color(.73f,.79f,.72f),TextAnchor.MiddleCenter);confirm=ConfirmButton(modal,460,622,360,53);confirmText.text=game.rewardRemaining>1?"确认修炼 · 选择第二份奖励":"确认修炼 · 进入下一波";UpdateSelection();Refresh();
  }
  public void UpdateSelection(){
   if(game.phase!=GamePhase.Rest||cards.Count!=3)return;bool chosen=game.pendingUpgrade!=null;
   for(int i=0;i<cards.Count;i++){bool selected=game.offers[i]==game.pendingUpgrade;cardGroups[i].alpha=chosen&&!selected?.65f:1;cardFrames[i].Select(selected);}
   confirm.interactable=chosen;cardHealth.text=$"气血 {game.hp:0.#} / {game.MaxHP:0.#} · 三选一，确认前可更换";
   if(!chosen){cardPreview.text="点击一张卡修炼 · 不限选择时间";return;}
   var u=Array.Find(game.data.upgrades,v=>v.id==game.pendingUpgrade);var copy=game.run.Clone();float preview=Rules.Apply(game.data,copy,u.id,game.hp);
   cardHealth.text=$"气血 {game.hp:0.#} → {preview:0.#} / {copy.maxHp:0.#} · 确认后生效";
   cardPreview.text=$"已选「{u.name}」· 可改选 · 确认后继续";
  }
  public void ShowFormationDamage(float damage,float x,float y,bool heavy){if(!formationFeedback)return;feedbackAt=game.clock;feedbackUntil=game.clock+.65f;feedbackX=x+62;feedbackY=y-66;feedbackPunch=heavy?1.3f:1.16f;formationFeedback.text=$"{damage:0.#}";formationFeedback.gameObject.SetActive(true);}
  public void ClearFormationDamage(){feedbackUntil=-1;if(formationFeedback)formationFeedback.gameObject.SetActive(false);}
  void RefreshFormationDamage(){if(!formationFeedback)return;bool show=game.clock<feedbackUntil&&!HasModal&&game.phase==GamePhase.Play;formationFeedback.gameObject.SetActive(show);if(!show)return;var viewport=game.gameCamera.WorldToViewportPoint(PixelWorld.Position(feedbackX,feedbackY));formationFeedback.rectTransform.anchoredPosition=new Vector2(viewport.x*1280-55,-((1-viewport.y)*720-24));float age=game.clock-feedbackAt;formationFeedback.rectTransform.localScale=Vector3.one*Mathf.Lerp(feedbackPunch,1,Mathf.Clamp01(age/.16f));formationFeedback.color=new Color(1,.87f,.60f,Mathf.Clamp01((feedbackUntil-game.clock)/.2f));}
  void MakeHUD(){hud=Rect("江湖状态",root,0,0,1280,720);formationFeedback=Label(hud,"",0,0,110,48,29,new Color(1,.87f,.60f),TextAnchor.MiddleCenter);var damageOutline=formationFeedback.gameObject.AddComponent<Outline>();damageOutline.effectColor=new Color(.03f,.10f,.10f);damageOutline.effectDistance=new Vector2(2,-2);formationFeedback.gameObject.SetActive(false);Box(hud,14,14,315,90,new Color(.025f,.09f,.1f,.86f));Art(hud,"taiji","0",18,21,67,67);hpText=Label(hud,"气血",92,20,220,25,19,pale);Box(hud,92,59,210,15,new Color(.15f,.2f,.19f));hpFill=Box(hud,93,60,208,13,new Color(.65f,.25f,.21f));placeText=Label(hud,"",20,105,520,35,19,pale);MakeCD("K", "飞剑往返",150,out kText,out kFill);MakeCD("L","万剑归宗",207,out lText,out lFill);prompt=Label(hud,"",390,612,500,42,23,pale,TextAnchor.MiddleCenter);notice=Label(hud,"",365,564,550,40,21,gold,TextAnchor.MiddleCenter);home=Button(hud,"H · 返回主页",1088,18,175,42,game.ShowMenu);home.GetComponentInChildren<Text>().fontSize=18;bossPanel=Rect("首领血条",hud,365,17,715,93);Box(bossPanel,0,0,715,93,new Color(.035f,.03f,.045f,.88f));bossName=Label(bossPanel,"",75,7,565,33,24,gold,TextAnchor.MiddleCenter);Box(bossPanel,75,47,565,22,new Color(.16f,.055f,.1f));bossFill=Box(bossPanel,77,49,561,18,new Color(.67f,.14f,.24f));Art(bossPanel,"masterSkull","0",8,6,58,78);Art(bossPanel,"masterSkull","0",649,6,58,78);warningPlate=Scroll(hud,457,116,610,70,false,2);bossWarning=Label(warningPlate,"",14,3,582,31,21,ink,TextAnchor.MiddleCenter);Box(warningPlate,20,48,390,7,new Color(.32f,.26f,.3f,.3f));novaBar=Box(warningPlate,20,48,390,7,new Color(.57f,.21f,.47f));novaCountdown=Label(warningPlate,"",425,34,167,28,18,ink,TextAnchor.MiddleCenter);for(int i=0;i<worldHints.Length;i++)worldHints[i]=Label(hud,"",0,0,200,34,16,pale,TextAnchor.MiddleCenter);for(int i=0;i<game.data.upgrades.Length;i++){var tile=Rect("已学天赋 · "+game.data.upgrades[i].id,hud,16,274,28,28);Box(tile,0,0,28,28,new Color(.68f,.58f,.35f,.85f));Box(tile,1,1,26,26,new Color(.035f,.1f,.11f,.95f));var im=Art(tile,game.art.UpgradeSheet(game.data.upgrades[i].id),game.data.upgrades[i].id,3,3,22,22);var level=Label(tile,"",17,17,10,11,10,new Color(1,.96f,.82f),TextAnchor.MiddleCenter);level.resizeTextForBestFit=false;level.fontSize=10;var shadow=level.gameObject.AddComponent<Shadow>();shadow.effectColor=new Color(0,0,0,.9f);shadow.effectDistance=new Vector2(1,-1);talentTiles.Add(tile);talentLevels.Add(level);learned.Add(im);tile.gameObject.SetActive(false);}}
  void MakeCD(string key,string label,float y,out Text text,out Image fill){Box(hud,16,y,244,49,new Color(.02f,.08f,.09f,.88f));Label(hud,key,24,y+3,29,40,25,gold,TextAnchor.MiddleCenter);text=Label(hud,label,62,y+3,185,24,18,pale);Box(hud,62,y+31,185,8,new Color(.13f,.2f,.22f));fill=Box(hud,62,y+31,185,8,teal);}
  public void SetPrompt(string text)=>prompt.text=text;
  public void Refresh(){if(!hud)return;RefreshFormationDamage();bool active=game.phase!=GamePhase.Menu&&game.phase!=GamePhase.Story;hud.gameObject.SetActive(active);if(!active)return;hpText.text=$"气血  {game.hp:0.#} / {game.MaxHP:0.#}";hpFill.rectTransform.sizeDelta=new Vector2(208*Mathf.Clamp01(game.hp/game.MaxHP),13);placeText.text=game.endless?$"轮回剑境 · 第 {game.run.wave} 波{game.ReinforcementLabel}":game.data.rooms[game.room].name;CD(kText,kFill,"飞剑",game.rangedReady,game.settings.rangedCooldown*game.Cooldown,true);CD(lText,lFill,"万剑",game.formationReady,game.settings.formationCooldown*game.Cooldown,game.formationLearned);notice.text=game.clock<game.noticeUntil?game.notice:"";bool show=game.boss!=null&&game.boss.active&&game.boss.hp>0;bossPanel.gameObject.SetActive(show);bossWarning.text=show?game.BossWarning:"";warningPlate.gameObject.SetActive(!HasModal&&!string.IsNullOrEmpty(bossWarning.text));bool nova=show&&game.boss.state=="novaTell";novaBar.rectTransform.sizeDelta=new Vector2(nova?390*game.NovaProgress:0,7);novaCountdown.text=nova?$"{Mathf.Max(0,game.boss.next-game.clock):0.0} 秒后爆发":"";if(show){bool master=game.boss.kind=="master";bossName.text=master?"魔灵老祖 · 玄衡":"镇山傀儡";bossName.color=master?new Color(.94f,.64f,.7f):gold;bossFill.color=master?new Color(.67f,.14f,.24f):new Color(.55f,.41f,.21f);bossFill.rectTransform.sizeDelta=new Vector2(561*game.boss.hp/game.boss.maxHp,18);foreach(var image in bossPanel.GetComponentsInChildren<Image>())if(image.name=="masterSkull")image.enabled=master;}
   float left=game.gameCamera.transform.position.x*100-640;for(int i=0;i<worldHints.Length;i++)worldHints[i].text="";if(game.SheltersVisible){for(int i=0;i<2;i++){worldHints[i].text="归元草 · 护心庇所";worldHints[i].rectTransform.anchoredPosition=new Vector2(game.ShelterXs[i]-left-100,-474);}}else if(!game.endless&&game.room==1){worldHints[0].text="↓ 藏剑石窟";worldHints[0].rectTransform.anchoredPosition=new Vector2(3222-left-100,-440);worldHints[1].text=game.dashLearned?"跳跃 → Shift 越崖":"断桥 · 需踏云诀";worldHints[1].rectTransform.anchoredPosition=new Vector2(3800-left-100,-450);}else if(!game.endless&&game.room==2){worldHints[0].text="藏剑遗卷";worldHints[0].rectTransform.anchoredPosition=new Vector2(game.data.shrineX-left-100,-385);}int visibleTalents=0;for(int i=0;i<learned.Count;i++){int level=game.run?.Level(game.data.upgrades[i].id)??0;talentTiles[i].gameObject.SetActive(level>0);if(level>0){talentTiles[i].anchoredPosition=new Vector2(16+visibleTalents%3*32,-(274+visibleTalents/3*32));talentLevels[i].text=level>1?level.ToString():"";visibleTalents++;}}if(unlockPortrait)unlockPortrait.rectTransform.anchoredPosition=new Vector2(125,-150+Mathf.Sin((Time.unscaledTime-animAt)*1.5f)*6);}
  void CD(Text text,Image fill,string name,float ready,float duration,bool unlocked){float remain=Mathf.Max(0,ready-game.clock);text.text=!unlocked?name+" · 未悟":remain>0?$"{name} · {remain:0.0} 秒":name+" · 可用";fill.rectTransform.sizeDelta=new Vector2(unlocked?185*(1-Mathf.Clamp01(remain/duration)):0,8);fill.color=remain>0?gold:teal;}
  public void FitScreen(){float ratio=Screen.width/(float)Mathf.Max(1,Screen.height),target=16f/9;game.gameCamera.rect=ratio>target?new Rect((1-target/ratio)/2,0,target/ratio,1):new Rect(0,(1-ratio/target)/2,1,ratio/target); // Center a fixed design surface within wide/tall displays.
   root.pivot=new Vector2(.5f,.5f);if(modal)modal.anchoredPosition=new Vector2((root.rect.width-1280)/2,-(root.rect.height-720)/2);if(hud)hud.anchoredPosition=new Vector2((root.rect.width-1280)/2,-(root.rect.height-720)/2);}
 }
}
