using System;using System.Collections.Generic;using UnityEngine;
namespace Wuxia {
 public static class NativeObject {public static void Remove(UnityEngine.Object o){if(!o)return;if(Application.isPlaying)UnityEngine.Object.Destroy(o);else UnityEngine.Object.DestroyImmediate(o);}}
 public partial class WuxiaGame:MonoBehaviour {
  public GameSettings settings;public GamePhase phase=GamePhase.Menu;public int room,deaths,checkpointRoom;public float hp=5,clock;public bool endless,dashLearned,formationLearned,stoneDefeated,masterDefeated,skipSimulation;
  public RogueState run;public GameData data;public Actor player,boss;public readonly List<Actor> enemies=new List<Actor>();public readonly List<PlatformView> platforms=new List<PlatformView>();
  public string[] offers;public string pendingUpgrade;public int rewardRemaining=1,rewardTotal=1;public float rangedReady,formationReady,invincibleUntil,dashUntil,hurtUntil;public int facing=1;
  public float Width=>endless?2000:data.rooms[room].width;public float MaxHP=>run!=null?run.maxHp:5;public float DamageScale=>run?.DamageScale??1;public float Cooldown=>run?.CooldownScale??1;
  public bool SheltersVisible=>boss!=null&&boss.kind=="master"&&boss.hp>0;public float[] ShelterXs=>endless?new[]{430f,1570f}:new[]{220f,1080f};
  [NonSerialized] public bool automatedPlayback;[NonSerialized] public InputFrame playbackInput;
  public bool Initialized {get;private set;}public Camera gameCamera;public NativeUI ui;public ArtLibrary art;public GameAudio audio;public EffectPool fx;public int LastTestSeed=20261004;
  Transform worldRoot,effectRoot;SpriteView background,sword,swordBehind,sleeve,meleeArc,sealOuter,sealInner;readonly List<SpriteView> herbs=new List<SpriteView>();
  SpriteView healPickup;bool healTaken;System.Random random;InputFrame input;float dashReady,dashVY,lastGround=-100,jumpBuffer=-100,attackAt=-100,castAt=-100,walkClock,restUntil,deadUntil,formationAt=-100,shakeUntil,shakePower;
  bool castFired;int attackFacing=1;float checkpointX=247.5f,checkpointFeet=620;readonly HashSet<Actor> meleeHits=new HashSet<Actor>();float cameraLeft;public string notice="";public float noticeUntil;
  void Awake()=>Initialize();
  public void Initialize(){if(Initialized)return;Initialized=true;settings=settings?settings:Resources.Load<GameSettings>("Data/GameSettings");if(!settings)settings=ScriptableObject.CreateInstance<GameSettings>();data=GameData.Load();art=new ArtLibrary();art.Prewarm();Time.fixedDeltaTime=1/60f;Time.maximumDeltaTime=.1f;QualitySettings.vSyncCount=1;random=new System.Random(Application.isBatchMode?LastTestSeed:Environment.TickCount);Physics2D.gravity=new Vector2(0,-settings.gravity/100);Physics2D.simulationMode=SimulationMode2D.Script;Physics2D.IgnoreLayerCollision(8,8);Physics2D.IgnoreLayerCollision(8,10);Physics2D.IgnoreLayerCollision(10,10);Physics2D.IgnoreLayerCollision(9,10);
   var cg=new GameObject("像素相机");cg.transform.SetParent(transform);gameCamera=cg.AddComponent<Camera>();gameCamera.tag="MainCamera";gameCamera.orthographic=true;gameCamera.orthographicSize=3.6f;gameCamera.clearFlags=CameraClearFlags.SolidColor;gameCamera.backgroundColor=new Color(.035f,.075f,.075f);cg.transform.position=new Vector3(6.4f,3.6f,-10);cg.AddComponent<AudioListener>();
   effectRoot=new GameObject("有上限的特效池").transform;effectRoot.SetParent(transform);fx=new EffectPool(art,effectRoot);audio=gameObject.AddComponent<GameAudio>();audio.Initialize(settings.musicVolume);ui=gameObject.AddComponent<NativeUI>();ui.Initialize(this);ShowMenu();
  }
  void Update(){if(!Initialized||skipSimulation)return;ui.FitScreen();if(automatedPlayback){input=playbackInput;return;}if(Input.GetKeyDown(KeyCode.M))audio.ToggleMute();if(Input.GetKeyDown(KeyCode.H)&&phase!=GamePhase.Menu){ShowMenu();return;}if(Input.GetKeyDown(KeyCode.Escape)){if(phase==GamePhase.Play){phase=GamePhase.Paused;audio.Pause(true);ui.ShowPause();}else if(phase==GamePhase.Paused)Resume();}
   bool enter=Input.GetKeyDown(KeyCode.Return)||Input.GetKeyDown(KeyCode.E)||Input.GetKeyDown(KeyCode.Space);
   if(enter&&phase==GamePhase.Menu){ShowStory();return;}if(enter&&phase==GamePhase.Story){StartStory();return;}if(enter&&phase==GamePhase.Guide){FinishGuide();return;}if(enter&&phase==GamePhase.Unlock){FinishUnlock();return;}if(enter&&phase==GamePhase.Paused){Resume();return;}
   input.move=(Input.GetKey(KeyCode.D)||Input.GetKey(KeyCode.RightArrow)?1:0)-(Input.GetKey(KeyCode.A)||Input.GetKey(KeyCode.LeftArrow)?1:0);input.jump|=Input.GetKeyDown(KeyCode.Space);input.jumpHeld=Input.GetKey(KeyCode.Space);input.attack=Input.GetKey(KeyCode.J);input.ranged|=Input.GetKeyDown(KeyCode.K);input.dash|=Input.GetKeyDown(KeyCode.LeftShift)||Input.GetKeyDown(KeyCode.RightShift);input.ward|=Input.GetKeyDown(KeyCode.L);input.interact|=Input.GetKeyDown(KeyCode.E);
  }
  void FixedUpdate(){if(!Initialized||skipSimulation)return;Step(Time.fixedDeltaTime,input);input.jump=input.ranged=input.dash=input.ward=input.interact=false;}
  void LateUpdate(){if(!Initialized||skipSimulation)return;float alpha=phase==GamePhase.Play||phase==GamePhase.WaveClear?Mathf.Clamp01((Time.time-Time.fixedTime)/Time.fixedDeltaTime):1;art.Render(alpha);if(player!=null){UpdateCamera(Time.deltaTime,player.RenderX(alpha));ui.Refresh();}}
  public void Step(float dt,InputFrame controls){dt=Mathf.Clamp(dt,0,.05f);if(phase==GamePhase.Dead){clock+=dt;if(clock>=deadUntil){EnterRoom(checkpointRoom,checkpointX,checkpointFeet);hp=5;phase=GamePhase.Play;ui.Refresh();}return;}if(phase!=GamePhase.Play&&phase!=GamePhase.WaveClear)return;
   art.BeginStep();player.BeginStep();foreach(var actor in enemies)actor.BeginStep();boss?.BeginStep();clock+=dt;fx.Tick(clock,dt);bool clear=phase==GamePhase.WaveClear;MovePlayer(controls,dt);if(!clear){UpdateEnemies(dt);UpdateBoss(dt);UpdateRogue(dt);}UpdateProjectiles(dt);UpdateFormation(dt);
   Physics2D.SyncTransforms();Physics2D.Simulate(dt);ClampActors();if(boss!=null&&boss.hp>0&&boss.state=="masterNova")UpdateNovaHit();if(!clear&&phase==GamePhase.Play)ContactDamage();if(player.Feet>835)Damage(true,player.X);if(phase==GamePhase.Play){if(endless&&Targets().Count==0)FinishWave();else if(!endless)Interactions(controls.interact);}if(phase==GamePhase.WaveClear&&clock>=restUntil)ShowCards();RenderActors();RefreshHerbs();if(skipSimulation)UpdateCamera(dt);ui.Refresh();
  }
  void MovePlayer(InputFrame c,float dt){if(player.Grounded)lastGround=clock;if(c.jump)jumpBuffer=clock;if(jumpBuffer>clock-.13f&&lastGround>clock-.11f&&clock>=dashUntil){player.VY=-settings.jumpSpeed;jumpBuffer=lastGround=-100;audio.Play("jump");}
   if(!c.jumpHeld&&player.VY<-205&&clock>=dashUntil)player.VY+=settings.gravity*dt*1.8f;
   if(c.dash&&dashLearned&&!SwordAway()&&clock>=dashReady&&clock-castAt>=.57f){if(c.move!=0)facing=(int)c.move;dashVY=player.VY;dashUntil=clock+settings.dashDuration;dashReady=clock+settings.dashCooldown;attackAt=-100;audio.Play("dash");fx.Burst(player.X,player.CenterY,9,Color.cyan,clock);}
   if(clock<dashUntil){player.body.gravityScale=0;player.VX=facing*settings.dashSpeed;player.VY=0;}else{if(player.body.gravityScale==0){player.body.gravityScale=1;player.VY=dashVY;}bool busy=clock-attackAt<.39f||clock-castAt<.57f;if(c.move!=0&&!busy)facing=(int)c.move;if(clock>=hurtUntil)player.VX=c.move*settings.moveSpeed*(busy?.42f:1);}
   bool free=!SwordAway()&&clock-attackAt>=.39f&&clock-castAt>=.57f&&clock>=dashUntil&&clock>=hurtUntil;
   if(c.ranged&&free&&clock>=rangedReady){castAt=clock;castFired=false;attackFacing=facing;rangedReady=clock+settings.rangedCooldown*Cooldown;}else if(c.attack&&free){attackAt=clock;attackFacing=facing;meleeHits.Clear();if(run!=null)run.melees++;}
   if(c.ward&&formationLearned&&clock>=formationReady&&clock>=dashUntil&&clock>=hurtUntil)CastFormation();if(clock-castAt>=.26f&&clock-castAt<.57f&&!castFired){castFired=true;SpawnProjectile(player.X+attackFacing*36,player.CenterY-13,attackFacing>0?0:Mathf.PI,false);audio.Play("slash");}
   if(player.Grounded&&clock>=dashUntil)walkClock+=Mathf.Min(Mathf.Abs(player.VX)/24,10)*dt;Melee();
  }
  void ClampActors(){float lo=endless&&boss!=null?373:13,hi=endless&&boss!=null?1627:Width-13;var pos=player.body.position;pos.x=Mathf.Clamp(player.X,lo,hi)/100;player.body.position=pos;}
  public void ShowMenu(){ClearLevel();endless=false;run=null;phase=GamePhase.Menu;clock=0;notice="";audio.Stop();background=new SpriteView(art,transform,"主界面山门",-100);background.Image("ruins","0",640,360,1280,720);cameraLeft=0;gameCamera.transform.position=new Vector3(6.4f,3.6f,-10);ui.ShowMenu();}
  public void ShowStory(){phase=GamePhase.Story;ui.ShowStory();}
  void ResetRun(){ClearLevel();clock=0;hp=5;deaths=0;healTaken=false;dashLearned=formationLearned=stoneDefeated=masterDefeated=false;endless=false;run=null;rangedReady=formationReady=0;checkpointRoom=0;checkpointX=247.5f;checkpointFeet=620;facing=1;dashReady=0;walkClock=0;soundedAttack=echoAttack=orbitHitAt=-100;shakeUntil=shakePower=0;notice="";noticeUntil=0;audio.Pause(false);audio.StartMusic();}
  public void StartStory(){ResetRun();EnterRoom(0,247.5f,620);Guide();}
  public void StartTraining(){ResetRun();dashLearned=formationLearned=true;EnterRoom(3,180,620);SpawnEnemy(new EnemyData{kind="crawler",x=690,y=580,min=610,max=850});SpawnEnemy(new EnemyData{kind="moth",x=940,y=420,min=900,max=1030});Guide();}
  public void StartFinal(){ResetRun();dashLearned=formationLearned=true;EnterRoom(4,150,620);Guide();}
  public void StartEndless(){ResetRun();endless=true;stoneDefeated=masterDefeated=true;run=new RogueState{best=PlayerPrefs.GetInt("WuxiaEndlessBest",0)};hp=10;dashLearned=formationLearned=true;BeginWave();Guide();}
  void Guide(){phase=GamePhase.Guide;ui.ShowGuide();}public void FinishGuide(){phase=GamePhase.Play;ui.HideModal();audio.Pause(false);}
  public void Resume(){phase=GamePhase.Play;audio.Pause(false);ui.HideModal();}
  public void EnterRoom(int index,float x,float feet){ClearLevel();room=index;phase=GamePhase.Play;worldRoot=new GameObject("关卡 · "+data.rooms[index].name).transform;worldRoot.SetParent(transform);BuildWorld();player=new Actor(art,worldRoot,"白衣剑客","player",x,feet,26,58);sword=new SpriteView(art,worldRoot,"腰间护手与剑柄",21);swordBehind=new SpriteView(art,worldRoot,"衣袍后方剑身",18);sleeve=new SpriteView(art,worldRoot,"近侧手臂遮挡",22);meleeArc=new SpriteView(art,worldRoot,"随剑挥砍弧光",24);meleeArc.Visible(false);foreach(var e in data.rooms[index].enemies)SpawnEnemy(e);if(!endless&&index==3&&!stoneDefeated)SpawnBoss("golem",1130);if(!endless&&index==4&&!masterDefeated){dashLearned=formationLearned=true;SpawnBoss("master",820);}if(index==3||index==4){checkpointRoom=index;checkpointX=index==3?180:150;checkpointFeet=620;}if(index==1){checkpointRoom=1;checkpointX=x;checkpointFeet=620;}if(index==2&&!dashLearned){checkpointRoom=2;checkpointX=x;checkpointFeet=620;}attackAt=castAt=-100;hurtUntil=dashUntil=0;lastGround=jumpBuffer=-100;invincibleUntil=clock+.75f;cameraLeft=Mathf.Clamp(x-400,0,Mathf.Max(0,Width-1280));Physics2D.SyncTransforms();RefreshHerbs();RenderActors();art.BeginStep();UpdateCamera(0);ui.HideModal();audio.Boss(boss!=null);}
  void BuildWorld(){background=new SpriteView(art,worldRoot,"山川背景",-100);background.Color(new Color(.73f,.78f,.79f));background.Image(room==4?"finalBg":"roomAtlas",room==4?"0":room.ToString(),640,360,1280,720);PlatformData[] terrain=endless?new[]{new PlatformData{x=0,y=620,w=2000,h=210},new PlatformData{x=450,y=480,w=230,h=28},new PlatformData{x=1320,y=480,w=230,h=28}}:data.rooms[room].platforms;foreach(var p in terrain)AddPlatform(p);
   if(!endless){foreach(var exit in data.rooms[room].exits)Decor("gate",exit.x,620,100,160);if(room==2)Decor("altar",data.shrineX,620,110,160);if(room==3)Decor("altar",1735,620,110,160);if(room==4)Decor("altar",1190,620,90,140);}
   for(float x=230;x<Width;x+=470)Decor("altar",x,617,33,57);if(!endless&&room==1&&!healTaken){healPickup=Decor("herb",data.healX,336,39,42);}if(room==4)foreach(float x in ShelterXs){var herb=Decor("herb",x,615,52,57);herbs.Add(herb);herb.Visible(false);}
  }
  SpriteView Decor(string name,float x,float feet,float w,float h){var view=new SpriteView(art,worldRoot,"布景 · "+name,12);view.Image("wuxiaAtlas",name,x,feet-h/2,w,h);return view;}
  void AddPlatform(PlatformData data){float h=data.h>0?data.h:data.y==620?210:28;var p=new PlatformView{data=new PlatformData{x=data.x,y=data.y,w=data.w,h=h}};p.root=new GameObject(data.y==620?"地面":"可碎高台");p.root.layer=9;p.root.transform.SetParent(worldRoot);p.root.transform.position=PixelWorld.Position(data.x+data.w/2,data.y+h/2);p.collider=p.root.AddComponent<BoxCollider2D>();p.collider.size=new Vector2(data.w/100,h/100);p.collider.sharedMaterial=Actor.Surface;p.top=new SpriteView(art,p.root.transform,"台面贴图",14);p.top.renderer.sprite=data.y==620?art.Sprite("wuxiaAtlas","stoneTop"):art.Sprite("templeLedge");p.top.renderer.drawMode=SpriteDrawMode.Tiled;p.top.renderer.size=new Vector2(data.w/100,.28f);p.top.root.transform.position=PixelWorld.Position(data.x+data.w/2,data.y+14);if(data.y==620){p.fill=new SpriteView(art,p.root.transform,"石砖填充",10);p.fill.renderer.sprite=art.Sprite("wuxiaAtlas","stoneFill");p.fill.renderer.drawMode=SpriteDrawMode.Tiled;p.fill.renderer.size=new Vector2(data.w/100,(h-28)/100);p.fill.root.transform.position=PixelWorld.Position(data.x+data.w/2,data.y+28+(h-28)/2);}if(data.y!=620){for(int i=0;i<2;i++){var cap=new SpriteView(art,p.root.transform,"玉扣 · 台沿",15);cap.Image("templeCap","0",data.x+(i==0?7:data.w-7),data.y+14,14,28);cap.renderer.flipX=i==1;p.trim.Add(cap);}}platforms.Add(p);}
  void SpawnEnemy(EnemyData e){var actor=new Actor(art,worldRoot,e.kind=="moth"?"御剑纸鹤":"黑衣山匪",e.kind,e.x,e.y+(e.kind=="moth"?17.5f:18.5f),e.kind=="moth"?43:48,e.kind=="moth"?35:37);actor.hp=actor.maxHp=e.kind=="moth"?2:3;actor.min=e.min;actor.max=e.max;actor.baseY=e.y;enemies.Add(actor);}
  void SpawnBoss(string kind,float x){boss=new Actor(art,worldRoot,kind=="master"?"魔灵老祖 · 玄衡":"镇山傀儡",kind,x,620,kind=="master"?90:172,kind=="master"?150:176);boss.hp=boss.maxHp=kind=="master"?150:120;boss.entered=clock;}
  public void BeginWave(){if(run==null)return;run.wave++;ClearCombat();foreach(var enemy in enemies)enemy.Destroy();enemies.Clear();if(boss!=null){boss.Destroy();boss=null;}if(worldRoot==null||room!=4){EnterRoom(4,170,620);}else{foreach(var p in platforms){p.broken=false;p.collider.enabled=true;p.Visible(true);}player.Place(170,620);attackAt=castAt=-100;dashUntil=hurtUntil=0;}
   phase=GamePhase.Play;var spec=Rules.Wave(run.wave);if(spec.boss!=null){SpawnBoss(spec.boss,1000);boss.hp=boss.maxHp=Mathf.Round((spec.boss=="master"?150:120)*spec.bossScale);boss.active=true;ChangeBoss("recover",2.2f);player.Place(500,620);cameraLeft=360;}else for(int i=0;i<spec.count;i++){SpawnEnemy(new EnemyData{kind=i%3==2?"moth":"crawler",x=570+i%5*255,y=i%3==2?370+i%2*55:560,min=70,max=1930});enemies[enemies.Count-1].hp=enemies[enemies.Count-1].maxHp=Mathf.Ceil((i%3==2?3:4)*spec.hpScale);}
   rangedReady=formationReady=clock;invincibleUntil=clock+2.1f;run.nextOrbit=clock+.8f;run.nextThunder=clock+2.2f;run.nextFrost=clock+2.8f;run.shieldReady=clock;Physics2D.SyncTransforms();RefreshHerbs();ui.HideModal();audio.Boss(boss!=null);RenderActors();art.BeginStep();UpdateCamera(0);}
  public void FinishWave(){if(run==null||phase!=GamePhase.Play)return;run.cleared=run.wave;run.best=Mathf.Max(run.best,run.wave);PlayerPrefs.SetInt("WuxiaEndlessBest",run.best);hp=Mathf.Min(MaxHP,hp+run.Level("lotus")*.6f);rewardRemaining=rewardTotal=Rules.Wave(run.wave).boss!=null?2:1;phase=GamePhase.WaveClear;restUntil=clock+settings.clearRestDuration;ClearCombat();audio.Boss(false);Notice("此波已破 · 调息片刻",4.5f);}
  public void ShowCards(){phase=GamePhase.Rest;offers=Rules.Offers(data,run,random);pendingUpgrade=null;ui.ShowCards();}
  public void ChooseCard(string id){if(phase!=GamePhase.Rest||Array.IndexOf(offers,id)<0)return;pendingUpgrade=id;ui.UpdateSelection();}
  public void ConfirmCard(){if(phase!=GamePhase.Rest||pendingUpgrade==null)return;string id=pendingUpgrade;pendingUpgrade=null;hp=Rules.Apply(data,run,id,hp);audio.Play("heal");rewardRemaining--;if(rewardRemaining>0)ShowCards();else BeginWave();}
  public void FinishUnlock(){dashLearned=formationLearned=true;rangedReady=formationReady=clock;hp=5;checkpointRoom=2;checkpointX=data.shrineX-160;checkpointFeet=620;phase=GamePhase.Play;ui.HideModal();Notice("已悟踏云诀与万剑归宗 · 御剑越崖",3);}
  void Interactions(bool press){if(room==1&&!healTaken&&Mathf.Abs(player.X-data.healX)<50&&Mathf.Abs(player.CenterY-315)<65){healTaken=true;hp=MaxHP;healPickup?.Visible(false);audio.Play("heal");Notice("归元草 · 气血已满",2);}string text="";Action action=null;if(room==2&&!dashLearned&&Mathf.Abs(player.X-data.shrineX)<100){text="E 参悟剑诀";action=()=>{phase=GamePhase.Unlock;audio.Play("heal");ui.ShowUnlock();};}else if(room==3&&stoneDefeated&&player.X>1650){text="E 开启禁庭";action=()=>EnterRoom(4,150,620);}else if(room==4&&masterDefeated&&player.X>1080){text="E 完成归元封印";action=()=>{phase=GamePhase.Won;ui.ShowWon();};}else foreach(var exit in data.rooms[room].exits){if(Mathf.Abs(player.X-exit.x)>80)continue;text=exit.requiresDash&&!dashLearned?"需踏云诀":"E "+exit.label;if(!exit.requiresDash||dashLearned)action=()=>EnterRoom(exit.to,exit.spawnX,exit.spawnY+29);break;}
   ui.SetPrompt(text);if(press)action?.Invoke();}
  public void Notice(string text,float duration=2){notice=text;noticeUntil=clock+duration;}
  void RefreshHerbs(){foreach(var h in herbs)h.Visible(SheltersVisible);}
  public bool Sheltered(){if(!SheltersVisible||player.Feet<560)return false;foreach(float x in ShelterXs)if(Mathf.Abs(player.X-x)<=82)return true;return false;}
  void UpdateCamera(float dt,float renderX=float.NaN){float px=float.IsNaN(renderX)?player.X:renderX;float target=endless&&boss!=null?360:Mathf.Clamp(px-500,0,Mathf.Max(0,Width-1280));cameraLeft=Mathf.Lerp(cameraLeft,target,1-Mathf.Exp(-dt*8));var pos=new Vector3((cameraLeft+640)/100,3.6f,-10);if(clock<shakeUntil){pos.x+=Mathf.Sin(clock*127)*shakePower/100;pos.y+=Mathf.Cos(clock*111)*shakePower/100;}gameCamera.transform.position=pos;if(background!=null)background.root.transform.position=PixelWorld.Position(cameraLeft+640,360);}
  public void Shake(float strength,float duration){shakePower=strength;shakeUntil=clock+duration;}
  void ClearLevel(){ClearCombat();fx?.Clear();if(player!=null)player.Disable();foreach(var e in enemies)e.Disable();boss?.Disable();if(worldRoot){art.ForgetWorld(worldRoot);worldRoot.gameObject.SetActive(false);NativeObject.Remove(worldRoot.gameObject);}else if(background!=null)background.Destroy();worldRoot=null;player=boss=null;enemies.Clear();platforms.Clear();herbs.Clear();background=sword=swordBehind=sleeve=meleeArc=healPickup=null;}
  void OnDestroy(){if(!Initialized)return;fx.Dispose();art.Dispose();Physics2D.simulationMode=SimulationMode2D.FixedUpdate;}
 }
}
