using System;using System.Collections.Generic;using UnityEngine;
namespace Wuxia {
 public partial class WuxiaGame {
  class Projectile {public SpriteView view;public float x,y,angle,born,speed,range,damage;public bool hostile,tracking,returning,qi,rain;public HashSet<Actor> hits=new HashSet<Actor>();}
  class FlyingSword {public SpriteView view;public float x,y,angle,born,launch;public bool launched;public Actor target;public float orbitAngle,radius;public LineRenderer trail;public Vector3[] history=new Vector3[9];public int historyCount;}
  class GroundWave {public SpriteView view;public float x,born;public int dir;public bool strong;}
  readonly List<Projectile> projectiles=new List<Projectile>();readonly List<FlyingSword> formation=new List<FlyingSword>();readonly List<GroundWave> waves=new List<GroundWave>();readonly List<SpriteView> orbit=new List<SpriteView>();
  float soundedAttack=-100,echoAttack=-100,orbitHitAt=-100;int formationHits;public int ProjectileCount=>projectiles.Count+formation.Count+waves.Count;public float FormationDamage {get;private set;}public float LastStrikeDamage {get;private set;}
  readonly List<Actor> liveTargets=new List<Actor>(24);
  public List<Actor> Targets(){var result=liveTargets;result.Clear();foreach(var e in enemies)if(e.hp>0)result.Add(e);if(boss!=null&&boss.active&&boss.hp>0)result.Add(boss);return result;}
  bool SwordAway(){foreach(var p in projectiles)if(!p.hostile&&!p.qi&&!p.rain)return true;return false;}
  void Melee(){float age=clock-attackAt;if(age<.1f||age>=.235f)return;if(soundedAttack!=attackAt){soundedAttack=attackAt;audio.Play("slash");}
   if(run!=null&&run.Level("echo")>0&&run.melees%3==0&&echoAttack!=attackAt){echoAttack=attackAt;SpawnQi();}
   var area=new Rect(player.X+attackFacing*48-48,player.CenterY-50,96,90);foreach(var t in Targets())if(!meleeHits.Contains(t)&&area.Overlaps(t.Bounds)){meleeHits.Add(t);Strike(t,attackFacing);}
  }
  public void Strike(Actor t,int dir,bool ranged=false,float amount=-1){if(t==null||t.hp<=0)return;t.hitAt=clock;bool isBoss=t==boss;float dmg=amount>=0?amount:ranged?(isBoss?9:3):(isBoss&&(t.state=="recover"||t.state=="wallStun")?4:2);bool critical=run!=null&&run.CriticalChance>0&&random.NextDouble()<run.CriticalChance;float finalDamage=dmg*DamageScale*(critical?1.65f:1);LastStrikeDamage=finalDamage;t.hp=Mathf.Max(0,t.hp-finalDamage);if(critical){ui.ShowFormationDamage(finalDamage,t.X,t.CenterY,true);fx.Sprite("swordImpact","0",t.X,t.CenterY,95,95,clock,.2f,new Color(1,.84f,.52f,.7f),additive:true);}audio.Play("hit");if(!ranged)fx.Animated("pixelHit",6,t.X,Mathf.Clamp(player.CenterY,t.Bounds.yMin+10,t.Bounds.yMax-10),72,89,clock,.24f,Color.white,follow:t);if(amount<0)Shake(1.8f,.07f);
   if(!isBoss){t.VX=dir*150;t.windup=0;t.chargeUntil=clock-.001f;if(t.hp<=0){if(run!=null){run.kills++;if(run.kills%3==0)hp=Mathf.Min(MaxHP,hp+run.Level("blood")*.5f);}fx.Burst(t.X,t.CenterY,18,new Color(.55f,.78f,.7f),clock);t.Disable();}}
   else if(t.hp<=0){t.Disable();if(t.kind=="master")masterDefeated=true;else stoneDefeated=true;Shake(7,.3f);fx.Burst(t.X,t.CenterY,40,new Color(1,.8f,.5f),clock);audio.Play("heavy");audio.Boss(false);RefreshHerbs();Notice(endless?(PendingEnemies>0||LivingEnemies()>0?"首领已破 · 清除魔门伏兵":"破阵 · 双重机缘"):"封印已破 · 向前继续",3);}
  }
  public bool Damage(bool fall,float from,bool pierceDash=false,float custom=-1){if(phase!=GamePhase.Play&&phase!=GamePhase.WaveClear)return false;if(!fall&&(clock<invincibleUntil||(!pierceDash&&clock<dashUntil)))return false;
   int shield=run?.Level("shield")??0;if(!fall&&shield>0&&clock>=run.shieldReady){run.shieldReady=clock+12-(shield-1)*2;invincibleUntil=clock+.35f;fx.Ring(player.X,player.CenterY,112,112,new Color(1,.85f,.45f),clock,.4f,4);audio.Play("heavy");return false;}
   float incoming=custom>=0?custom:endless?Rules.Wave(run.wave).damage:1;if(!fall)incoming*=run?.IncomingScale??1;hp-=incoming;hp=Mathf.Max(0,hp);audio.Play("heavy");Shake(4,.16f);invincibleUntil=clock+settings.invincibleDuration;hurtUntil=clock+.22f;dashUntil=0;player.body.gravityScale=1;player.VX=(player.X>=from?1:-1)*190;player.VY=-170;fx.Burst(player.X,player.CenterY,12,new Color(1,.48f,.4f),clock);
   if(hp<=0){if(run!=null&&run.Level("revive")>0&&!run.revived){run.revived=true;hp=MaxHP*.5f;player.Place(170,620);invincibleUntil=clock+3.5f;fx.Ring(player.X,player.CenterY,180,180,new Color(1,.9f,.5f),clock,.7f,4);Notice("涅槃归真",2);return true;}deaths++;ClearCombat();player.VX=player.VY=0;if(endless){phase=GamePhase.EndlessOver;ui.ShowEndlessOver();}else{phase=GamePhase.Dead;deadUntil=clock+1.1f;Notice("气血已尽 · 返回山门",1.1f);}}
   else if(fall){player.Place(checkpointRoom==room?checkpointX:170,checkpointRoom==room?checkpointFeet:620);invincibleUntil=clock+1.8f;}return true;
  }
  void ContactDamage(){foreach(var e in enemies){if(e.hp<=0||clock<e.spawnGraceUntil)continue;Rect hit=e.Bounds;if(!e.IsFlying)hit=new Rect(e.X-e.width/2,e.Feet-76,e.width,76);if(player.Bounds.Overlaps(hit))Damage(false,e.X,custom:e.attackPower);}if(boss==null||!boss.active||boss.hp<=0)return;if(boss.kind=="master"){if(player.Bounds.Overlaps(boss.Bounds))Damage(false,boss.X);return;}var p=player.Bounds;float dx=boss.X-Mathf.Clamp(boss.X,p.xMin,p.xMax),dy=boss.Feet-Mathf.Clamp(boss.Feet,p.yMin,p.yMax);if(p.yMin<boss.Feet&&dx*dx/(72*72)+dy*dy/(172*172)<1)Damage(false,boss.X);}
  void SpawnProjectile(float x,float y,float angle,bool hostile,bool tracking=false,float damage=-1){if(projectiles.Count>=48)return;projectiles.Add(new Projectile{view=new SpriteView(art,effectRoot,tracking?"追魂魔符":hostile?"赤焰飞刃":"往返飞剑",26),x=x,y=y,angle=angle,born=clock,hostile=hostile,tracking=tracking,damage=damage,speed=tracking?250:hostile?235:610});}
  void SpawnQi(){if(projectiles.Count>=48)return;int n=run.Level("echo");projectiles.Add(new Projectile{view=new SpriteView(art,effectRoot,"沧浪剑气",28),x=player.X+attackFacing*40,y=player.CenterY-12,angle=attackFacing>0?0:Mathf.PI,born=clock,speed=760,range=650+n*90,damage=3+n*2,qi=true});fx.Burst(player.X,player.CenterY,12,new Color(.7f,1,.85f),clock);Shake(2.5f,.1f);}
  bool Blocked(float x,float y){foreach(var p in platforms)if(!p.broken&&p.data.h>28&&new Rect(p.data.x,p.data.y,p.data.w,p.data.h).Contains(new Vector2(x,y)))return true;return false;}
  static float Turn(float current,float target,float step)=>current+Mathf.Clamp(Mathf.DeltaAngle(current*Mathf.Rad2Deg,target*Mathf.Rad2Deg)*Mathf.Deg2Rad,-step,step);
  void UpdateProjectiles(float dt){for(int i=projectiles.Count-1;i>=0;i--){var p=projectiles[i];float age=clock-p.born,old=p.x,oldY=p.y;bool gone=false;if(p.tracking&&age<1.5f)p.angle=Turn(p.angle,Mathf.Atan2(player.CenterY-14-p.y,player.X-p.x),2*dt);
    if(!p.hostile&&!p.qi&&!p.rain){if(!p.returning&&(age>=.65f||p.x<0||p.x>Width||Blocked(p.x,p.y)))p.returning=true;if(p.returning){float dx=player.X+facing*12-p.x,dy=player.CenterY-13-p.y;if(dx*dx+dy*dy<1600||age>2.4f)gone=true;else{p.angle=Mathf.Atan2(dy,dx);p.speed=850;}}}
    p.x+=Mathf.Cos(p.angle)*p.speed*dt;p.y+=Mathf.Sin(p.angle)*p.speed*dt;
    if(p.rain){foreach(var t in Targets())if(SegmentContact(new Vector2(old,oldY),new Vector2(p.x,p.y),t.Bounds,9,out var contact)){Strike(t,p.x>=player.X?1:-1,true,p.damage);SwordImpact(contact.x,contact.y,p.angle,false);gone=true;break;}gone|=age>1.6f||p.y>690;p.view.Image("blade","0",p.x,p.y,8,76,p.angle+Mathf.PI/2);p.view.Color(new Color(.83f,1,.9f));fx.Line(new[]{new Vector2(p.x-Mathf.Cos(p.angle)*45,p.y-Mathf.Sin(p.angle)*45),new Vector2(p.x,p.y)},2,new Color(.7f,.95f,.78f,.5f),clock,.06f);}
    else if(p.qi){foreach(var t in Targets())if(!p.hits.Contains(t)&&SegmentHits(new Vector2(old,oldY),new Vector2(p.x,p.y),t.Bounds,32)){p.hits.Add(t);Strike(t,Mathf.Cos(p.angle)>0?1:-1,true,p.damage);SwordImpact(t.X,t.CenterY,p.angle,false);}gone|=age*p.speed>p.range||p.x<0||p.x>Width;bool left=Mathf.Cos(p.angle)<0;p.view.Image("qiSlash",(3+Mathf.FloorToInt(age/.08f)%3).ToString(),p.x,p.y,125,120,left?p.angle-Mathf.PI:p.angle);p.view.renderer.flipX=left;p.view.Color(new Color(.65f,1,.84f,Mathf.Clamp01((p.range-age*p.speed)/100)));}
    else if(p.hostile){gone|=age>3.6f||p.x<0||p.x>Width||Blocked(p.x,p.y);if(!gone&&SegmentHits(new Vector2(old,oldY),new Vector2(p.x,p.y),player.Bounds,8)){Damage(false,p.x,custom:p.damage);gone=true;}if(p.tracking){p.view.Image("wuxiaAtlas","talisman",p.x,p.y,25,45,p.angle+Mathf.PI/2);p.view.Color(new Color(.9f,.65f,1));}else p.view.Image("enemyBlade","0",p.x,p.y,17,59,p.angle+Mathf.PI/2);fx.Line(new[]{new Vector2(p.x-Mathf.Cos(p.angle)*38,p.y-Mathf.Sin(p.angle)*38),new Vector2(p.x,p.y)},2,p.tracking?new Color(.75f,.4f,1,.55f):new Color(1,.4f,.2f,.5f),clock,.06f);}
    else {if(!p.returning)foreach(var t in Targets())if(SegmentContact(new Vector2(old,oldY),new Vector2(p.x,p.y),t.Bounds,10,out var contact)){Strike(t,Mathf.Cos(p.angle)>0?1:-1,true);p.returning=true;SwordImpact(contact.x,contact.y,p.angle,true);break;}p.view.Image("blade","0",p.x,p.y,9,86,p.angle+Mathf.PI/2);fx.Line(new[]{new Vector2(p.x-Mathf.Cos(p.angle)*42,p.y-Mathf.Sin(p.angle)*42),new Vector2(p.x,p.y)},2,new Color(.6f,.95f,.9f,.48f),clock,.06f);}
    if(gone){p.view.Destroy();projectiles.RemoveAt(i);}
   }
   for(int i=waves.Count-1;i>=0;i--){var w=waves[i];float oldX=w.x;w.x+=w.dir*(w.strong?360:245)*dt;float h=w.strong?36:25;var hurt=new Rect(Mathf.Min(oldX,w.x)-(w.strong?25:15),601-h/2,Mathf.Abs(w.x-oldX)+(w.strong?50:30),h);if(hurt.Overlaps(player.Bounds))Damage(false,w.x);float visualH=w.strong?70:49+Mathf.Sin((clock-w.born)*20)*3;w.view.Image("wuxiaAtlas","spikes",w.x,624-visualH/2,w.strong?130:87,visualH);w.view.renderer.flipX=w.dir<0;w.view.Color(w.strong?new Color(.73f,.63f,.91f):Color.white);if(Mathf.FloorToInt(clock*60)%4==0)fx.Sprite("wuxiaAtlas","stoneTop",w.x-w.dir*22,617,5,4,clock,.3f,new Color(.76f,.68f,.58f),-w.dir*32,-48,true);if(w.x<0||w.x>Width||clock-w.born>4.8f){w.view.Destroy();waves.RemoveAt(i);}}
  }
  void SpawnWave(float x,int dir,bool strong=false){if(waves.Count<20)waves.Add(new GroundWave{view=new SpriteView(art,effectRoot,"破土震荡波",25),x=x,dir=dir,strong=strong,born=clock});}
  void DestroyFormationSword(FlyingSword s){s.view.Destroy();if(s.trail)NativeObject.Remove(s.trail.gameObject);}
  void CastFormation(){formationAt=clock;formationReady=clock+settings.formationCooldown*Cooldown;formationHits=0;FormationDamage=0;ui.ClearFormationDamage();foreach(var s in formation)DestroyFormationSword(s);formation.Clear();
   for(int i=0;i<12;i++){float a=i*Mathf.PI/6-Mathf.PI/2;var view=new SpriteView(art,effectRoot,"万剑 · "+i,30);view.Additive();formation.Add(new FlyingSword{view=view,x=player.X+Mathf.Cos(a)*48,y=player.CenterY-70+Mathf.Sin(a)*48*.78f,angle=a,orbitAngle=a,born=clock,launch=clock+.42f+i*.035f});}
   if(sealOuter==null){sealOuter=new SpriteView(art,effectRoot,"归宗法阵 · 外环",16);sealInner=new SpriteView(art,effectRoot,"归宗法阵 · 内环",17);sealGlow=new SpriteView(art,effectRoot,"归宗法阵 · 柔光",15);sealOuter.Additive();sealInner.Additive();sealGlow.Additive(true,true);}audio.Play("heavy");Shake(3,.13f);
  }
  void SwordTrail(FlyingSword s){
   if(!s.trail){var go=new GameObject("万剑 · 渐变剑轨");go.transform.SetParent(effectRoot,false);s.trail=go.AddComponent<LineRenderer>();s.trail.sharedMaterial=art.AdditiveMaterial;s.trail.useWorldSpace=true;s.trail.sortingOrder=29;s.trail.numCapVertices=3;s.trail.numCornerVertices=3;s.trail.widthCurve=AnimationCurve.Linear(0,.024f,1,.052f);var gradient=new Gradient();gradient.SetKeys(new[]{new GradientColorKey(new Color(.5f,.84f,.77f),0),new GradientColorKey(new Color(.97f,.89f,.63f),1)},new[]{new GradientAlphaKey(0,0),new GradientAlphaKey(.65f,1)});s.trail.colorGradient=gradient;}
   if(s.historyCount==9){for(int i=0;i<8;i++)s.history[i]=s.history[i+1];}else s.historyCount++;
   s.history[s.historyCount-1]=PixelWorld.Position(s.x,s.y);s.trail.positionCount=s.historyCount;for(int i=0;i<s.historyCount;i++)s.trail.SetPosition(i,s.history[i]);
  }
  Actor Nearest(float x,float y,float range,bool prioritizeBoss=false){if(prioritizeBoss&&boss!=null&&boss.active&&boss.hp>0&&Vector2.Distance(new Vector2(x,y),new Vector2(boss.X,boss.CenterY))<=range)return boss;Actor nearest=null;float distance=range*range;foreach(var t in Targets()){float d=(t.X-x)*(t.X-x)+(t.CenterY-y)*(t.CenterY-y);if(d<distance){distance=d;nearest=t;}}return nearest;}
  void UpdateFormation(float dt){float age=clock-formationAt;if(sealOuter!=null){bool show=age>=0&&age<1.12f;sealOuter.Visible(show);sealInner.Visible(show);sealGlow.Visible(show);if(show){float rise=Mathf.Clamp01(age/.35f),release=age<.42f?0:Mathf.Max(0,1-(age-.42f)/.22f),fade=age<.68f?1:1-(age-.68f)/.44f,scale=.45f+.55f*(1-Mathf.Pow(1-rise,3))+release*.12f,alpha=Mathf.Min(1,rise*1.4f)*fade*.88f,x=player.X-facing*12,y=player.CenterY-88;
    sealOuter.Image("formationOuter","0",x,y,246*scale,246*scale,age*.38f);sealInner.Image("formationInner","0",x,y,224*scale,224*scale,-age*.55f);sealGlow.Image("whitePixel","0",x,y,(150+release*90)*scale,(150+release*90)*scale);sealOuter.Color(new Color(1,1,1,alpha));sealInner.Color(new Color(1,1,1,alpha));sealGlow.Color(new Color(.67f,.90f,.82f,alpha*(.18f+release*.48f)));}}
   for(int i=formation.Count-1;i>=0;i--){var s=formation[i];bool gone=clock-s.born>3.3f;
    if(clock>=s.launch){
     if(!s.launched){s.launched=true;s.target=Nearest(s.x,s.y,2000,true);s.angle=s.target!=null?Mathf.Atan2(s.target.CenterY-s.y,s.target.X-s.x):facing>0?0:Mathf.PI;if(i==formation.Count-1)Shake(4,.17f);}
     if(s.target!=null&&(s.target.hp<=0||!s.target.body.simulated))s.target=null;
     if(s.target==null)s.target=Nearest(s.x,s.y,2000,true);
     var before=new Vector2(s.x,s.y);float speed=Mathf.Lerp(560,1050,Mathf.Clamp01((clock-s.launch)/.5f));
     if(s.target!=null){var aim=new Vector2(s.target.X,s.target.CenterY);float wanted=Mathf.Atan2(aim.y-s.y,aim.x-s.x);s.angle=Turn(s.angle,wanted,9*dt);if(Vector2.Distance(before,aim)<110){var next=Vector2.MoveTowards(before,aim,speed*dt);s.x=next.x;s.y=next.y;s.angle=wanted;}else{s.x+=Mathf.Cos(s.angle)*speed*dt;s.y+=Mathf.Sin(s.angle)*speed*dt;}}
     else {s.x+=Mathf.Cos(s.angle)*speed*dt;s.y+=Mathf.Sin(s.angle)*speed*dt;}
     SwordTrail(s);
     foreach(var t in Targets())if(SegmentContact(before,new Vector2(s.x,s.y),t.Bounds,12,out var contact)){Strike(t,Mathf.Cos(s.angle)>0?1:-1,true,2);formationHits++;FormationDamage+=LastStrikeDamage;bool heavy=formationHits==1||formationHits==12||t.hp<=0;SwordImpact(contact.x,contact.y,s.angle,heavy);ui.ShowFormationDamage(FormationDamage,contact.x,contact.y,heavy);gone=true;break;}
    }else {float a=s.orbitAngle+Mathf.Sin(age*3)*.12f,r=48+Mathf.Min(1,age/.32f)*44;s.angle=a;s.x=player.X+Mathf.Cos(a)*r;s.y=player.CenterY-70+Mathf.Sin(a)*r*.78f;}
    s.view.Image("blade","0",s.x,s.y,10,76,s.angle+Mathf.PI/2);s.view.Color(new Color(.85f,1,.94f,Mathf.Min(1,age/.16f)));if(gone){DestroyFormationSword(s);formation.RemoveAt(i);}
   }
  }
  void SwordImpact(float x,float y,float angle,bool heavy){
   fx.Sprite("swordImpact","0",x,y,heavy?176:118,heavy?176:118,clock,heavy?.29f:.18f,new Color(.85f,1,.93f,heavy?.88f:.55f),angle:angle+formationHits*.28f,additive:true,grow:1.35f);
   fx.Sprite("swordPierce","0",x,y,heavy?260:190,heavy?68:42,clock,.22f,new Color(1,.94f,.79f,.65f),Mathf.Cos(angle)*227,Mathf.Sin(angle)*227,angle:angle,additive:true);
   if(heavy){Shake(4.5f,.18f);audio.Play("heavy");}
  }
  // Place impacts at the segment entry point, rather than an already overshot frame endpoint.
  public static bool SegmentHits(Vector2 from,Vector2 to,Rect bounds,float padding)=>SegmentContact(from,to,bounds,padding,out _);
  public static bool SegmentContact(Vector2 from,Vector2 to,Rect bounds,float padding,out Vector2 contact){var visible=bounds;contact=to;bounds.xMin-=padding;bounds.yMin-=padding;bounds.xMax+=padding;bounds.yMax+=padding;float lo=0,hi=1;var delta=to-from;for(int axis=0;axis<2;axis++){float origin=axis==0?from.x:from.y,d=axis==0?delta.x:delta.y,min=axis==0?bounds.xMin:bounds.yMin,max=axis==0?bounds.xMax:bounds.yMax;if(Mathf.Abs(d)<.00001f){if(origin<min||origin>max)return false;}else{float a=(min-origin)/d,b=(max-origin)/d;if(a>b){float tmp=a;a=b;b=tmp;}lo=Mathf.Max(lo,a);hi=Mathf.Min(hi,b);if(lo>hi)return false;}}contact=from+delta*lo;contact.x=Mathf.Clamp(contact.x,visible.xMin,visible.xMax);contact.y=Mathf.Clamp(contact.y,visible.yMin,visible.yMax);return true;}
  void UpdateRogue(float dt){if(run==null)return;UpdateNewRogueSkills();int n=run.Level("orbit"),count=n>0?n+1:0;while(orbit.Count<count)orbit.Add(new SpriteView(art,effectRoot,"护体飞剑",25));while(orbit.Count>count){orbit[orbit.Count-1].Destroy();orbit.RemoveAt(orbit.Count-1);}for(int i=0;i<orbit.Count;i++){float a=clock*2.5f+i*Mathf.PI*2/count,x=player.X+Mathf.Cos(a)*90,y=player.CenterY+Mathf.Sin(a)*62;orbit[i].Image("blade","0",x,y,8,58,a+Mathf.PI/2);if(clock>=orbitHitAt)foreach(var t in Targets())if(Mathf.Abs(t.X-x)<35&&Mathf.Abs(t.CenterY-y)<(t==boss?90:45)){Strike(t,t.X>player.X?1:-1,true,1+n);orbitHitAt=clock+.55f;break;}}
   n=run.Level("thunder");if(n>0&&clock>=run.nextThunder){run.nextThunder=clock+5*Cooldown;var targets=Targets();targets.Sort((a,b)=>Mathf.Abs(a.X-player.X).CompareTo(Mathf.Abs(b.X-player.X)));for(int i=0;i<Mathf.Min(Mathf.CeilToInt(n/2f),targets.Count);i++){var t=targets[i];if(Mathf.Abs(t.X-player.X)>730)continue;fx.Line(new[]{new Vector2(t.X-22,100),new Vector2(t.X+14,270),new Vector2(t.X-12,390),new Vector2(t.X,t.CenterY)},5,new Color(.88f,.87f,1),clock,.3f);Strike(t,1,true,5+3*n);Shake(3,.15f);}}
   n=run.Level("frost");if(n>0&&clock>=run.nextFrost){run.nextFrost=clock+6*Cooldown;float radius=150+n*25;fx.Animated("pixelMist",24,player.X,player.CenterY,160,130,clock,.42f,Color.white);foreach(var t in Targets())if(Mathf.Abs(t.X-player.X)<radius){t.frozenUntil=clock+2.2f;Strike(t,1,true,2+2*n);if(t.hp>0)fx.Animated("pixelFrost",36,t.X,t.CenterY,110,120,clock,2.2f,Color.white,follow:t,order:18);}}
  }
  void ClearCombat(){ClearReinforcements();ClearNewRogueSkills();ClearWorldEffects();foreach(var p in projectiles)p.view.Destroy();projectiles.Clear();foreach(var s in formation)DestroyFormationSword(s);formation.Clear();foreach(var w in waves)w.view.Destroy();waves.Clear();foreach(var o in orbit)o.Destroy();orbit.Clear();sealOuter?.Visible(false);sealInner?.Visible(false);sealGlow?.Visible(false);ui?.ClearFormationDamage();formationAt=-100;}
  public void RenderActors(){if(player==null)return;float age=clock-attackAt,castAge=clock-castAt;string sheet="hero";int frame=clock<hurtUntil?10:clock<dashUntil?9:castAge<.57f?(castAge<.26f?6:7):!player.Grounded?(player.VY<0?4:5):0;float scale=settings.heroHeight/art.Frame("hero","0").h;int dir=facing;
   if(age>=0&&age<.39f){sheet="heroAttack";frame=age<.1f?Mathf.Min(2,Mathf.FloorToInt(age/.034f)):age<.235f?3+Mathf.Min(2,Mathf.FloorToInt((age-.1f)/.045f)):age<.315f?6:7;scale=84f/315;dir=attackFacing;}else if(frame==0&&Mathf.Abs(player.VX)>5){sheet="heroRun";frame=Mathf.FloorToInt(walkClock)%8;scale=84f/400;}
   player.view.PoseActor(sheet,frame,player,scale,dir,clock<dashUntil?11:0);player.view.Color(new Color(1,1,1,clock<invincibleUntil&&Mathf.FloorToInt(clock*14)%2==0?.55f:1));bool attack=age>=0&&age<.39f,casting=castAge>=0&&castAge<.57f,weaponVisible=!SwordAway()&&!attack&&!casting;sword.Visible(weaponVisible);swordBehind.Visible(weaponVisible&&clock>=dashUntil);sleeve.Visible(false);
   if(clock<dashUntil){sword.Image("blade","0",player.X,player.Feet-5,9,110,dir*Mathf.PI/2);sword.Attach(player,sword.root.transform.position-(Vector3)player.body.position,sword.root.transform.rotation);}
   else if(weaponVisible){var f=art.Frame(sheet,frame.ToString());float a=-dir*2f,guardX=f.beltY>0?player.X+dir*(f.beltX-f.anchorX)*scale:player.X+dir*5,guardY=f.beltY>0?player.Feet+(f.beltY-f.baseline)*scale:player.Feet-48;float x=guardX+Mathf.Sin(a)*19.5f,y=guardY-Mathf.Cos(a)*19.5f;
    swordBehind.SwordSection(false,player,x,y,7,78,a);sword.SwordSection(true,player,x,y,7,78,a);swordBehind.Color(player.view.renderer.color);sword.Color(player.view.renderer.color);sleeve.MatchPose(player.view,art.Sleeve(sheet,frame.ToString()));sleeve.Color(player.view.renderer.color);sleeve.Visible(true);}
   bool arcVisible=age>=.095f&&age<.27f&&clock>=dashUntil;meleeArc.Visible(arcVisible);if(arcVisible){float sweep=Mathf.Clamp01((age-.095f)/.175f);meleeArc.Image("qiSlash",(3+Mathf.Min(2,Mathf.FloorToInt(sweep*3))).ToString(),player.X+dir*27,player.Feet-54+sweep*14,106,90);meleeArc.renderer.flipX=dir<0;meleeArc.Attach(player,meleeArc.root.transform.position-(Vector3)player.body.position,Quaternion.identity);meleeArc.Color(new Color(1,1,.9f,Mathf.Min(1,(.27f-age)*20)));}
   fx.FollowActors();
   foreach(var e in enemies){if(e.hp<=0)continue;if(RenderNewEnemy(e))continue;bool moth=e.kind=="moth";string s=moth?"craneMotion":"bandit";int f=moth?(e.windup>0?1:new[]{0,1,2,3,1,3}[Mathf.FloorToInt(clock/(clock<e.chargeUntil?.1f:.16f))%6]):clock-e.hitAt<.18f?7:e.windup>0?4:!e.landed?5:clock<e.chargeUntil?6:1;float k=moth?58f/art.Frame("craneMotion","0").h:84f/art.Frame("bandit","0").h;if(!moth&&e.windup<=0&&e.landed&&clock>=e.chargeUntil&&clock-e.hitAt>=.18f){s="banditRun";f=Mathf.FloorToInt((clock+e.min*.0001f)/.15f)%8;k=84f/347;}e.view.PoseActor(s,f,e,k,e.dir,moth?e.height*.5f:0);e.view.Color(clock-e.hitAt<.14f?new Color(1,.85f,.7f):clock<e.frozenUntil?new Color(.93f,.97f,1):Color.white);}
   if(boss!=null&&boss.hp>0){bool master=boss.kind=="master";float a=clock-boss.entered;int f=master?(boss.state=="sealTell"?1:boss.state=="masterCast"?2:boss.state=="masterSlamTell"?3:boss.state=="masterQuake"?4:boss.state=="novaTell"||boss.state=="masterNova"?5:boss.state=="recover"?6:0):clock-boss.hitAt<.16f?7:boss.state=="slamTell"?(a<.55f?1:2):boss.state=="slam"?3:boss.state=="charge"?4+Mathf.FloorToInt(a/.11f)%2:boss.state=="wallStun"?(a<.25f?7:6):boss.state=="recover"||boss.state=="brake"?6:0;string s=master?"masterAtlas":"bossAtlas";boss.view.PoseActor(s,f,boss,(master?184f:settings.stoneHeight)/art.Frame(s,"0").h,boss.dir);boss.view.Color(clock-boss.hitAt<.14f?new Color(1,.85f,.7f):Color.white);}
  }
 }
}
