using System;using System.Collections.Generic;using System.IO;using System.Reflection;using UnityEditor;using UnityEngine;
namespace Wuxia.Editor {
 public static class AnimationCombatValidation {
  static readonly List<string> passed=new List<string>();static WuxiaGame game;
  static void Check(bool ok,string name){if(!ok)throw new Exception("V13 FAILED: "+name);passed.Add(name);Debug.Log("PASS V13: "+name);}
  static void Tick(int n,InputFrame input=default){for(int i=0;i<n;i++){game.Step(1/60f,input);input.jump=input.ward=input.ranged=input.dash=false;}}
  static SpriteView View(string name)=>(SpriteView)typeof(WuxiaGame).GetField(name,BindingFlags.NonPublic|BindingFlags.Instance).GetValue(game);
  public static void Run(){passed.Clear();var root=new GameObject("动作与命中回归");try{game=root.AddComponent<WuxiaGame>();game.Initialize();game.skipSimulation=true;game.StartTraining();game.FinishGuide();game.invincibleUntil=10000;
    foreach(int dir in new[]{-1,1}){game.boss.Place(1000,620);game.boss.active=true;game.boss.dir=dir;game.boss.VX=-dir*240;game.boss.targetX=1000+dir*250;game.ChangeBoss("charge",2);Tick(6);Check(Mathf.Sign(game.boss.VX)==dir,"冲撞起步消除反向残余速度 "+dir);Check(game.boss.view.renderer.flipX==(dir>0),"原画朝左的石像在冲撞时面向实际行进方向 "+dir);float x=game.boss.X;game.player.Place(x-dir*180,620);Tick(5);Check(Mathf.Sign(game.boss.X-x)==dir&&game.boss.dir==dir,"玩家绕到身后不会使冲撞中途反向 "+dir);}
    game.boss.hp=0;game.boss.Disable();foreach(var e in game.enemies){e.hp=0;e.Disable();}game.player.Place(300,620);Tick(5);game.facing=1;Tick(8,new InputFrame{attack=true,jump=true,jumpHeld=true});var arc=View("meleeArc");Check(arc.renderer.enabled,"跳跃挥砍出现独立弧光图层");var before=arc.root.transform.position;float px=game.player.X,feet=game.player.Feet;game.player.Place(px+170,feet-90);game.RenderActors();var after=arc.root.transform.position;Check(Mathf.Abs(after.x-before.x-1.7f)<.001f&&Mathf.Abs(after.y-before.y-.9f)<.001f,"挥砍弧光随角色横向与垂直位移保持挂点");
    Tick(30);game.player.Place(400,620);Tick(6);game.facing=-1;Tick(8,new InputFrame{attack=true});Check(arc.renderer.enabled&&arc.renderer.flipX,"左向挥砍使用水平镜像而非倒置旋转");Tick(30);Check(!arc.renderer.enabled,"攻击结束后清理弧光显示");
    game.player.Place(300,620);Tick(6);var frames=new HashSet<string>();Tick(1,new InputFrame{move=1});for(int i=0;i<56;i++){game.Step(1/60f,new InputFrame{move=1});frames.Add(game.player.view.renderer.sprite.name);}Check(frames.Count==8&&game.player.view.renderer.sprite.name.StartsWith("heroRun13:"),"一个跑步周期完整播放八张新双腿帧");Tick(3);var sword=View("sword");var sleeve=View("sleeve");Check(game.player.view.renderer.sortingOrder<sword.renderer.sortingOrder&&sword.renderer.sortingOrder<sleeve.renderer.sortingOrder,"腰剑位于身体与近侧手臂之间");Check(Mathf.Abs(sword.root.transform.localScale.x*sword.renderer.sprite.rect.width-10)<.01f,"保留原剑贴图且剑柄投影宽度提高至十像素");Check(game.art.Frame("hero","0").arm.Length>=12,"近袖由独立轮廓遮罩提取，不使用整块躯干裁切");Finish();
   }catch(Exception e){Debug.LogException(e);if(Application.isBatchMode)EditorApplication.Exit(1);throw;}finally{UnityEngine.Object.DestroyImmediate(root);}}
  static void Finish(){Check(WuxiaGame.SegmentContact(new Vector2(0,30),new Vector2(300,30),new Rect(100,0,40,80),12,out var hit)&&Mathf.Abs(hit.x-100)<.001f,"高速剑命中点在敌人前缘而非穿过后的终点");Check(game.art.Frame("pixelFrost","35").w==100&&game.art.Frame("pixelHit","5").w==55,"CC0 霜晶36帧与金属命中6帧完整导入");for(int i=0;i<500;i++)game.fx.Animated("pixelHit",6,300,500,90,111,game.clock,.3f,Color.white);Check(game.fx.ActiveCount<=160,"升级特效复用固定池，连续命中保持对象数上限");game.fx.Clear();Check(game.fx.ActiveCount==0,"清关彻底关闭复用特效");Directory.CreateDirectory("Documentation/Validation");File.WriteAllText("Documentation/Validation/animation-combat-regression.txt",string.Join("\n",passed));Debug.Log("WUXIA_V13_OK "+passed.Count);}
 }
}
