using System;using System.Collections.Generic;using System.Reflection;using System.IO;using UnityEditor;using UnityEngine;
namespace Wuxia.Editor {
 public static class OcclusionTerrainValidation {
  static readonly List<string> passed=new List<string>();static WuxiaGame game;
  static void Check(bool ok,string message){if(!ok)throw new Exception("V14 FAILED: "+message);passed.Add(message);Debug.Log("PASS V14: "+message);}
  static SpriteView View(string field)=>(SpriteView)typeof(WuxiaGame).GetField(field,BindingFlags.Instance|BindingFlags.NonPublic).GetValue(game);
  static void Tick(int n,InputFrame input=default){for(int i=0;i<n;i++){game.Step(1/60f,input);input.jump=input.dash=false;}}
  public static void Run(){passed.Clear();var root=new GameObject("台底与剑身遮挡回归");try{game=root.AddComponent<WuxiaGame>();game.Initialize();game.skipSimulation=true;
   for(int room=0;room<5;room++){game.EnterRoom(room,170,620);game.invincibleUntil=10000;foreach(var e in game.enemies){e.hp=0;e.Disable();}if(game.boss!=null){game.boss.hp=0;game.boss.Disable();}var ledge=game.platforms.Find(p=>p.data.y<620);if(ledge==null)continue;float bottom=ledge.data.y+ledge.data.h;game.player.Place(ledge.data.x+ledge.data.w*.5f,bottom+game.player.TerrainHeight+2);game.player.VY=-740;Physics2D.SyncTransforms();Tick(2,new InputFrame{jumpHeld=true});float head=game.player.Feet-game.player.TerrainHeight;Check(head>=bottom-1.5f,"剧情关卡 "+room+" 跃起时完整头部被台底挡住");Check(game.player.VY>=-1,"剧情关卡 "+room+" 顶到台底后立即停止向上运动");}
   for(int room=0;room<4;room++){game.EnterRoom(room,170,620);foreach(var e in game.enemies){e.hp=0;e.Disable();}if(game.boss!=null){game.boss.hp=0;game.boss.Disable();}foreach(var upper in game.platforms)foreach(var lower in game.platforms)if(upper.data.y<lower.data.y&&upper.data.x<lower.data.x+lower.data.w&&upper.data.x+upper.data.w>lower.data.x)Check(lower.data.y-(upper.data.y+upper.data.h)>=game.player.TerrainHeight+8,"剧情 "+room+" 高台下方有足够站立净空 "+upper.data.x+"/"+lower.data.x);var low=game.platforms.Find(p=>p.data.y>=490&&p.data.y<620);if(low==null)continue;game.player.Place(low.data.x-70,620);Physics2D.SyncTransforms();Tick(Mathf.CeilToInt((low.data.w+140)/game.settings.moveSpeed*60),new InputFrame{move=1});Check(game.player.X>=low.data.x+low.data.w+50&&game.player.Feet<622,"剧情 "+room+" 可从低台下方完整走过，不被挤进地面");}
   game.StartTraining();game.FinishGuide();game.invincibleUntil=10000;game.boss.hp=0;game.boss.Disable();foreach(var e in game.enemies){e.hp=0;e.Disable();}game.player.Place(800,620);Tick(5);var body=game.player.view;var back=View("swordBehind");var hilt=View("sword");var sleeve=View("sleeve");Check(back.renderer.sortingOrder<body.renderer.sortingOrder&&body.renderer.sortingOrder<hilt.renderer.sortingOrder&&hilt.renderer.sortingOrder<sleeve.renderer.sortingOrder,"剑身、衣袍、护手剑柄、近侧袖臂分为四层");Check(back.renderer.sprite.texture==hilt.renderer.sprite.texture&&back.renderer.sprite.texture==game.art.Texture("blade"),"两段剑使用同一原图，没有换剑款或叠出第二把剑");
   foreach(int dir in new[]{-1,1}){game.facing=dir;game.RenderActors();game.art.Render(.25f);Check((sleeve.root.transform.position-body.root.transform.position).sqrMagnitude<.000001f,"袖臂在左/右朝向插值时与衣袍完全对齐 "+dir);Check(hilt.renderer.enabled&&back.renderer.enabled,"左/右朝向正常佩剑两段均显示 "+dir);}
   game.dashLearned=true;Tick(1,new InputFrame{dash=true,move=1});Check(hilt.renderer.enabled&&!back.renderer.enabled,"御剑只显示一把完整剑，隐藏腰间分段剑身");game.art.Render(.25f);var expected=Vector2.Lerp(game.player.previousPosition,game.player.body.position,.25f)+new Vector2(0,(5-game.player.height*.5f)/100);Check(Vector2.Distance(hilt.root.transform.position,expected)<.001f,"御剑开始不会从腰间插值穿过衣袍，直接保持脚下挂点");Tick(16);Check(back.renderer.enabled&&hilt.renderer.sprite.name=="blade:hilt","御剑结束恢复腰间的衣袍遮挡");
   var ledge2=game.platforms.Find(p=>p.data.y<620);game.player.Place(ledge2.data.x+ledge2.data.w*.5f,ledge2.data.y);Physics2D.SyncTransforms();Tick(5);Check(game.player.Grounded&&Mathf.Abs(game.player.Feet-ledge2.data.y)<2,"完整身高碰撞盒仍可正常站在高台上");Check(Mathf.Abs(game.player.collider.bounds.min.y-(720-game.player.Feet)/100)<.02f,"加高碰撞盒保持脚底位置与落点不变");game.ShowMenu();game.art.Render(.5f);Check(game.player==null,"切关清理新增剑身图层和角色引用");
   Directory.CreateDirectory("Documentation/Validation");File.WriteAllText("Documentation/Validation/occlusion-terrain-regression.txt",string.Join("\n",passed));Debug.Log("WUXIA_V14_OK "+passed.Count);
  }catch(Exception e){Debug.LogException(e);if(Application.isBatchMode)EditorApplication.Exit(1);throw;}finally{UnityEngine.Object.DestroyImmediate(root);}}
 }
}
