using System;using System.Collections;using System.Collections.Generic;using System.IO;using System.Reflection;using UnityEditor;using UnityEngine;
namespace Wuxia.Editor {
 public static class OptimizationValidation {
  static readonly List<string> passed=new List<string>();static WuxiaGame game;
  static void Check(bool ok,string description){if(!ok)throw new Exception("OPTIMIZATION FAILED: "+description);passed.Add(description);Debug.Log("PASS V2: "+description);}
  static void Tick(int count,InputFrame input=default){for(int i=0;i<count;i++){game.Step(1/60f,input);input.jump=input.dash=input.ward=input.ranged=false;}}
  public static void Run(){var root=new GameObject("优化回归检查");try{game=root.AddComponent<WuxiaGame>();game.Initialize();game.skipSimulation=true;Check(Mathf.Abs(Time.fixedDeltaTime-1/60f)<.00001f,"实际运行强制 60 Hz 物理步长，避免项目默认 50 Hz");game.StartTraining();game.FinishGuide();game.invincibleUntil=10000;game.boss.hp=0;foreach(var e in game.enemies){e.hp=0;e.Disable();}
   var ledge=game.platforms.Find(p=>p.data.y<620);game.player.Place(ledge.data.x-13.2f,ledge.data.y+35);Physics2D.SyncTransforms();Check(!game.player.Grounded,"台侧接触不被脚底检测误判为落地");Tick(18,new InputFrame{move=1,jumpHeld=true});Check(game.player.Feet>ledge.data.y+70,"顶住台侧仍正常下落，不因摩擦悬停");Check(game.player.collider.sharedMaterial.friction==0,"角色物理材质无摩擦且无弹性");game.player.Place(ledge.data.x+ledge.data.w/2,ledge.data.y);Tick(8);Check(game.player.Grounded,"高台上表面正常着地");game.player.Place(200,620);Tick(12);float maxDeviation=0;for(int i=0;i<180;i++){game.Step(1/60f,new InputFrame{move=i/30%2==0?1:-1});maxDeviation=Mathf.Max(maxDeviation,Mathf.Abs(game.player.Feet-620));}Check(maxDeviation<2,"地面左右连续换向不抖动碰撞高度");
   var view=new SpriteView(game.art,root.transform,"插值测试",0);view.Image("whitePixel","0",200,300,8,8);view.BeginStep();view.Image("whitePixel","0",300,300,8,8);view.Render(.25f);Check(Mathf.Abs(view.root.transform.position.x-2.25f)<.0001f,"角色/投射物图层可在两个物理位置间逐显示帧插值");view.Render(.75f);Check(Mathf.Abs(view.root.transform.position.x-2.75f)<.0001f,"插值进度连续，不局限于固定帧刷新");view.Destroy();Check(WuxiaGame.SegmentHits(new Vector2(0,0),new Vector2(200,0),new Rect(90,-10,4,20),0),"高速飞剑穿越薄碰撞盒仍命中");Check(!WuxiaGame.SegmentHits(new Vector2(0,40),new Vector2(200,40),new Rect(90,-10,4,20),0),"连续命中检测不会误伤旁边敌人");
   var waveMethod=typeof(WuxiaGame).GetMethod("SpawnWave",BindingFlags.NonPublic|BindingFlags.Instance);waveMethod.Invoke(game,new object[]{300,1,false});Tick(1);var waves=(IList)typeof(WuxiaGame).GetField("waves",BindingFlags.NonPublic|BindingFlags.Instance).GetValue(game);var waveView=(SpriteView)waves[0].GetType().GetField("view").GetValue(waves[0]);Check(waveView.renderer.sprite.name=="wuxiaAtlas:spikes","地震使用 HTML 原版破土尖石，非剑气占位图");Check(Mathf.Abs(waveView.root.transform.localScale.x*waveView.renderer.sprite.rect.width-87)<.01f,"原版普通地震图宽 87 像素恢复");
   game.StartTraining();game.FinishGuide();game.invincibleUntil=10000;game.boss.hp=0;foreach(var e in game.enemies)e.Destroy();game.enemies.Clear();var a=new Actor(game.art,root.transform,"目标甲","crawler",650,620,48,37){hp=100,maxHp=100,min=100,max=1800,windup=1000};var b=new Actor(game.art,root.transform,"目标乙","crawler",1200,620,48,37){hp=100,maxHp=100,min=100,max=1800,windup=1000};game.enemies.Add(a);game.enemies.Add(b);game.player.Place(400,620);Tick(28,new InputFrame{ward=true});var swords=(IList)typeof(WuxiaGame).GetField("formation",BindingFlags.NonPublic|BindingFlags.Instance).GetValue(game);object launched=null;foreach(var s in swords)if((bool)s.GetType().GetField("launched").GetValue(s)){launched=s;break;}Check(launched!=null,"万剑归宗进入发射阶段");var targetField=launched.GetType().GetField("target");Check(targetField.GetValue(launched)==a,"发射时锁定当前合适敌人");float sx=(float)launched.GetType().GetField("x").GetValue(launched),sy=(float)launched.GetType().GetField("y").GetValue(launched);b.Place(sx+10,sy-110+18.5f);Tick(2);Check(targetField.GetValue(launched)==a,"旁边出现更近目标时，已发射飞剑不突然掉头");a.hp=0;a.Disable();Tick(1);Check(targetField.GetValue(launched)==b,"原目标死亡后才重新索敌");
   game.StartFinal();game.FinishGuide();game.invincibleUntil=10000;game.player.Place(420,620);game.boss.active=true;game.ChangeBoss("recover",100);Tick(200,new InputFrame{ward=true});Check(game.FormationDamage>=22,"十二剑可靠追踪固定首领并造成至少十一剑伤害");Check(game.ProjectileCount==0,"飞剑结束后释放对象，没有滞留绕圈");
   game.StartFinal();game.FinishGuide();game.boss.active=true;game.invincibleUntil=-1;game.player.Place(400,620);float hp=game.hp;game.ChangeBoss("novaTell",.05f);Tick(10);Check(game.boss.state=="masterNova"&&game.hp==hp,"魔潮开始时不会全屏瞬间扣血，等待波前到达");Tick(38);Check(game.hp==hp-1,"离开庇所时波前经过造成一次伤害");game.StartFinal();game.FinishGuide();game.boss.active=true;game.invincibleUntil=-1;game.player.Place(220,620);hp=game.hp;game.ChangeBoss("novaTell",.05f);Tick(55);Check(game.hp==hp&&game.Sheltered(),"草庇所内完整承受魔潮扫过而不受伤");game.StartFinal();game.FinishGuide();game.boss.active=true;game.invincibleUntil=-1;game.player.Place(400,620);hp=game.hp;game.ChangeBoss("novaTell",.05f);Tick(45,new InputFrame{jump=true,jumpHeld=true});Check(game.hp==hp-1,"魔潮覆盖全高度，单纯跳跃不能代替草庇所");
   game.ui.ShowGuide();var papers=game.ui.GetComponentsInChildren<UnityEngine.UI.Image>();bool light=false;foreach(var image in papers)if(image.color.r>.85f&&image.color.g>.8f&&image.color.b>.65f&&image.color.a>.9f&&image.rectTransform.sizeDelta.x>500)light=true;Check(light,"引导卷轴使用浅米白底与深墨字");Check(game.art.Texture("jianMetal").height==151&&game.art.Frame("jadeSlash","5").w>0,"CC0 金属剑与完整六帧剑光均已导入");Check(game.art.Sprite("templeLedge").texture.width==64,"高台使用独立浅铜顶边的深木纹素材");game.ShowMenu();game.art.Render(.5f);int baselineViews=game.art.ViewCount;for(int i=0;i<8;i++){game.StartTraining();game.FinishGuide();Tick(2);game.art.Render(.5f);game.ShowMenu();game.art.Render(.5f);}Check(game.art.ViewCount==baselineViews,"反复切关/回主页会注销绘制对象，插值不访问已销毁图层且无注册泄漏");Directory.CreateDirectory("Documentation/Validation");File.WriteAllText("Documentation/Validation/optimization-regression.txt","Unity "+Application.unityVersion+"\n"+DateTime.Now+"\n"+string.Join("\n",passed));Debug.Log("WUXIA_OPTIMIZATION_OK "+passed.Count);
  }catch(Exception e){Debug.LogException(e);if(Application.isBatchMode)EditorApplication.Exit(1);throw;}finally{UnityEngine.Object.DestroyImmediate(root);}}
 }
}
