using System;using System.Collections.Generic;using System.IO;using UnityEngine;using UnityEditor;using UnityEngine.UI;
namespace Wuxia.Editor {
 public static class PortValidation {
  static WuxiaGame game;static List<string> passed=new List<string>();static void Check(bool ok,string name){if(!ok)throw new Exception("FAILED: "+name);passed.Add(name);Debug.Log("PASS: "+name);}
  static void Tick(int n,InputFrame input=default){for(int i=0;i<n;i++){game.Step(1/60f,input);input.jump=input.dash=input.ranged=input.ward=input.interact=false;}}
  public static void RunAndBuild(){Run();OptimizationValidation.Run();AnimationCombatValidation.Run();OcclusionTerrainValidation.Run();ProjectBuilder.BuildMac();}
  [MenuItem("武侠遗境/运行移植回归检查")]
  public static void Run(){passed.Clear();try {var root=new GameObject("迁移回归测试");game=root.AddComponent<WuxiaGame>();game.Initialize();game.skipSimulation=true;Check(game.phase==GamePhase.Menu,"原生菜单与中文资源加载");Check(Resources.Load<GameSettings>("Data/GameSettings")&&Resources.Load<GameContent>("Data/Content").rooms[4],"参数与五关布局为持久化 Unity 资产");Check(game.art.Frame("heroRun13","7").h>200,"完整角色八帧跑步图集");game.StartStory();Check(game.phase==GamePhase.Guide,"剧情开始及操作引导");game.FinishGuide();Tick(30);float startX=game.player.X;Tick(30,new InputFrame{move=1});Check(game.player.X>startX+90,"原生 Rigidbody2D 移动与地面碰撞");game.player.Place(300,620);Tick(10);float low=620;for(int i=0;i<90;i++){game.Step(1/60f,new InputFrame{jump=i==0,jumpHeld=true});low=Mathf.Min(low,game.player.Feet);}Check(low<440&&low>417,"长按跃起最高点恰好越过石像（高度约189像素）");
   var foe=game.enemies[0];foe.Place(game.player.X,game.player.Feet-35);game.invincibleUntil=-1;game.dashUntil=0;float hp=game.hp;Tick(1);Check(game.hp<hp,"山匪跃击扩展躯干命中有伤害");game.ShowMenu();game.StartEndless();game.FinishGuide();Check(game.boss==null&&!game.SheltersVisible,"第一波无首领、无护心草");game.run.wave=4;game.BeginWave();Check(game.boss.kind=="golem"&&!game.SheltersVisible,"第五波石像首领且无护心草");Check(game.platforms[1].data.w==230&&game.platforms[2].data.x+game.platforms[1].data.x+230==2000,"高台等长、左右对称并分列首领两侧");game.ChangeBoss("charge",3);game.boss.VX=300;game.BreakPlatform(game.platforms[1],-1);Check(game.platforms[1].broken&&!game.platforms[1].collider.enabled&&game.boss.VX==0&&game.boss.state=="wallStun","冲撞碎台、关闭碰撞、首领立即停下与硬直");
   game.BeginWave();game.run.wave=4;game.BeginWave();var slab=game.platforms[1];game.boss.dir=1;game.boss.Place(slab.data.x-130,620);game.boss.targetX=800;game.ChangeBoss("charge",3);game.player.Place(1500,620);Tick(80);Check(slab.broken&&game.boss.state=="wallStun"&&Mathf.Abs(game.boss.VX)<.1f,"真实物理模拟冲撞触发碎台且立即停下");game.run.wave=9;game.BeginWave();Check(game.boss.kind=="master"&&game.SheltersVisible,"第十波魔主出现两株护心草");game.RenderActors();Check(game.boss.view.root.transform.localScale.x>.3f&&game.boss.view.renderer.enabled,"首领缩放与可见模型正确");game.player.Place(430,620);Check(game.Sheltered(),"护心草庇护位置有效");game.player.Place(900,620);Check(!game.Sheltered(),"离开草庇所不受保护");var rnd=new System.Random(67);int last=-1;var skills=new HashSet<int>();for(int i=0;i<100;i++){int skill=Rules.MasterSkill(last,rnd);Check(skill!=last,"魔主随机技能无连续重复 #"+i);last=skill;skills.Add(skill);}Check(skills.Count==3,"三种魔主技能全部可抽取");
   game.StartStory();game.FinishGuide();game.player.Place(game.data.rooms[0].exits[0].x,620);Tick(1,new InputFrame{interact=true});Check(game.room==1,"山门交互进入第二关");game.EnterRoom(2,game.data.shrineX,620);Tick(1,new InputFrame{interact=true});Check(game.phase==GamePhase.Unlock,"石窟参悟打开传承卷轴");game.FinishUnlock();Check(game.dashLearned&&game.formationLearned,"传承同时解锁两项技能");game.StartFinal();game.FinishGuide();game.player.Place(420,620);Tick(2);Check(Mathf.Abs(game.player.X-420)<2,"瞬移同步原生 Transform 与 Rigidbody2D");game.boss.active=true;game.Strike(game.boss,1,true,10000);game.player.Place(1190,620);Tick(1,new InputFrame{interact=true});Check(game.phase==GamePhase.Won,"魔主战与归元结局可完成");game.StartEndless();game.FinishGuide();for(int wave=1;wave<=30;wave++){Check(game.run.wave==wave,"波次递进 #"+wave);foreach(var e in game.enemies)e.hp=0;if(game.boss!=null)game.boss.hp=0;game.FinishWave();float before=game.player.X;Tick(60,new InputFrame{move=1});Check(game.phase==GamePhase.WaveClear&&game.player.X>before+100,"清波自由移动 #"+wave);Tick(220);Check(game.phase==GamePhase.Rest&&game.offers.Length==3,"延迟后打开三选一 #"+wave);Check(game.rewardRemaining==(wave%5==0?2:1),"首领双奖励 #"+wave);while(game.phase==GamePhase.Rest){float prev=game.hp,cap=game.MaxHP;game.ChooseCard(game.offers[0]);game.ChooseCard(game.offers[1]);game.ChooseCard("heal");Check(game.hp==prev&&game.MaxHP==cap&&game.pendingUpgrade=="heal","改选不提前生效 #"+wave);var confirm=Array.Find(game.ui.GetComponentsInChildren<Button>(true),b=>b.name=="确认 · 进入下一步");Check(confirm!=null&&confirm.interactable,"原生鼠标确认按钮可交互 #"+wave);confirm.onClick.Invoke();}Check(game.phase==GamePhase.Play,"回春丹确认后继续运行 #"+wave);game.hp=game.MaxHP;}
   foreach(var u in game.data.upgrades)if(u.id!="heal"){float old=game.MaxHP;game.hp=Rules.Apply(game.data,game.run,u.id,game.hp);Check(game.run.Level(u.id)>0,"增益生效 "+u.name);}game.hp=.5f;game.Damage(true,game.player.X);Check(game.hp>0&&game.run.revived&&game.player.Feet<=620,"坠落濒死复苏回到安全地面");game.invincibleUntil=10000;Tick(600,new InputFrame{move=1,attack=true,jumpHeld=true,ward=true,ranged=true});Check(game.fx.ActiveCount<=160&&game.ProjectileCount<=80,"技能、投射物与特效数量受限");game.StartTraining();game.FinishGuide();Tick(120);Tick(1,new InputFrame{dash=true});game.ShowMenu();game.StartTraining();game.FinishGuide();Tick(1,new InputFrame{dash=true});Check(game.dashUntil>game.clock,"返回主页重开后身法冷却完全重置");game.ShowMenu();Check(game.enemies.Count==0&&game.platforms.Count==0&&game.player==null,"回主界面清理所有战斗对象");Directory.CreateDirectory("Documentation/Validation");File.WriteAllText("Documentation/Validation/regression.txt","Unity "+Application.unityVersion+"\n"+DateTime.Now+"\n"+string.Join("\n",passed));UnityEngine.Object.DestroyImmediate(root);Debug.Log("WUXIA_VALIDATION_OK "+passed.Count);}
   catch(Exception e){Debug.LogException(e);if(Application.isBatchMode)EditorApplication.Exit(1);throw;} }
 }
}
