using System;using System.IO;using UnityEngine;using UnityEditor;using UnityEditor.SceneManagement;using UnityEditor.Build.Reporting;
namespace Wuxia.Editor {
 public class WuxiaAssetImporter:AssetPostprocessor {
  void OnPreprocessTexture(){if(assetPath.StartsWith("Assets/Wuxia/AppIcon/")){var icon=(TextureImporter)assetImporter;icon.textureType=TextureImporterType.Default;icon.mipmapEnabled=false;icon.isReadable=true;icon.filterMode=FilterMode.Bilinear;icon.textureCompression=TextureImporterCompression.Uncompressed;icon.maxTextureSize=2048;icon.npotScale=TextureImporterNPOTScale.None;return;}if(!assetPath.StartsWith("Assets/Wuxia/Resources/Art/"))return;var t=(TextureImporter)assetImporter;t.textureType=TextureImporterType.Default;t.alphaIsTransparency=true;t.mipmapEnabled=false;t.isReadable=true;t.filterMode=FilterMode.Point;t.textureCompression=TextureImporterCompression.Uncompressed;t.maxTextureSize=4096;t.npotScale=TextureImporterNPOTScale.None;t.wrapMode=TextureWrapMode.Clamp;}
  void OnPreprocessAudio(){if(!assetPath.StartsWith("Assets/Wuxia/Resources/Audio/"))return;var a=(AudioImporter)assetImporter;var sample=a.defaultSampleSettings;sample.loadType=assetPath.Contains("music")?AudioClipLoadType.Streaming:AudioClipLoadType.DecompressOnLoad;sample.compressionFormat=assetPath.Contains("music")?AudioCompressionFormat.Vorbis:AudioCompressionFormat.PCM;sample.quality=.85f;a.defaultSampleSettings=sample;}
 }
 public static class ProjectBuilder {
  const string scene="Assets/Wuxia/Scenes/WuxiaMain.unity";
  [MenuItem("武侠遗境/重建项目场景与预制体")]
  public static void Setup(){AssetDatabase.Refresh();PlayerSettings.companyName="Wuxia Workshop";PlayerSettings.productName="武侠遗境";PlayerSettings.bundleVersion="1.7.1-unity";PlayerSettings.defaultScreenWidth=1280;PlayerSettings.defaultScreenHeight=720;PlayerSettings.fullScreenMode=FullScreenMode.Windowed;PlayerSettings.resizableWindow=true;PlayerSettings.runInBackground=true;PlayerSettings.colorSpace=ColorSpace.Gamma;PlayerSettings.SetScriptingBackend(UnityEditor.Build.NamedBuildTarget.Standalone,ScriptingImplementation.Mono2x);PlayerSettings.SetApiCompatibilityLevel(UnityEditor.Build.NamedBuildTarget.Standalone,ApiCompatibilityLevel.NET_Standard);var ps=new SerializedObject(AssetDatabase.LoadAllAssetsAtPath("ProjectSettings/ProjectSettings.asset")[0]);var input=ps.FindProperty("activeInputHandler");if(input!=null)input.intValue=0;ps.ApplyModifiedPropertiesWithoutUndo();
   var tags=new SerializedObject(AssetDatabase.LoadAllAssetsAtPath("ProjectSettings/TagManager.asset")[0]);tags.FindProperty("layers").GetArrayElementAtIndex(8).stringValue="Actors";tags.FindProperty("layers").GetArrayElementAtIndex(9).stringValue="Terrain";tags.FindProperty("layers").GetArrayElementAtIndex(10).stringValue="Projectiles";tags.ApplyModifiedProperties();Time.fixedDeltaTime=1/60f;Time.maximumDeltaTime=.1f;Physics2D.gravity=new Vector2(0,-14.5f);
   Directory.CreateDirectory("Assets/Wuxia/Resources/Prefabs");foreach(string name in new[]{"Player","Bandit","Crane","StoneGuardian","CorruptedMaster"}){var root=new GameObject(name);root.layer=8;var body=root.AddComponent<Rigidbody2D>();body.constraints=RigidbodyConstraints2D.FreezeRotation;body.gravityScale=name=="Crane"?0:1;body.collisionDetectionMode=CollisionDetectionMode2D.Continuous;body.sleepMode=RigidbodySleepMode2D.NeverSleep;var box=root.AddComponent<BoxCollider2D>();box.size=name=="StoneGuardian"?new Vector2(1.72f,1.76f):name=="CorruptedMaster"?new Vector2(.9f,1.5f):name=="Player"?new Vector2(.26f,.90f):name=="Crane"?new Vector2(.43f,.35f):new Vector2(.48f,.84f);box.offset=name=="Player"?new Vector2(0,.16f):name=="Bandit"?new Vector2(0,.235f):Vector2.zero;PrefabUtility.SaveAsPrefabAsset(root,"Assets/Wuxia/Resources/Prefabs/"+name+".prefab");UnityEngine.Object.DestroyImmediate(root);}
   var settings=AssetDatabase.LoadAssetAtPath<GameSettings>("Assets/Wuxia/Resources/Data/GameSettings.asset");if(!settings){settings=ScriptableObject.CreateInstance<GameSettings>();AssetDatabase.CreateAsset(settings,"Assets/Wuxia/Resources/Data/GameSettings.asset");}var raw=JsonUtility.FromJson<GameData>(Resources.Load<TextAsset>("Data/GameData").text);var content=AssetDatabase.LoadAssetAtPath<GameContent>("Assets/Wuxia/Resources/Data/Content.asset");if(!content){content=ScriptableObject.CreateInstance<GameContent>();content.rooms=new RoomAsset[raw.rooms.Length];for(int i=0;i<raw.rooms.Length;i++){var room=ScriptableObject.CreateInstance<RoomAsset>();room.layout=raw.rooms[i];AssetDatabase.CreateAsset(room,"Assets/Wuxia/Resources/Data/Room"+i+".asset");content.rooms[i]=room;}content.upgrades=raw.upgrades;content.shrineX=raw.shrineX;content.healX=raw.healX;AssetDatabase.CreateAsset(content,"Assets/Wuxia/Resources/Data/Content.asset");}var s=EditorSceneManager.NewScene(NewSceneSetup.EmptyScene,NewSceneMode.Single);var game=new GameObject("武侠遗境 · 原生游戏控制器").AddComponent<WuxiaGame>();game.settings=settings;EditorSceneManager.SaveScene(s,scene);EditorBuildSettings.scenes=new[]{new EditorBuildSettingsScene(scene,true)};AssetDatabase.SaveAssets();Debug.Log("WUXIA_SETUP_OK");}
  [MenuItem("武侠遗境/打开主场景")]
  public static void OpenScene()=>EditorSceneManager.OpenScene(scene);
  public static void ConfigureAppIcon(){AssetDatabase.Refresh();var icon=AssetDatabase.LoadAssetAtPath<Texture2D>("Assets/Wuxia/AppIcon/wuxia-app-icon.png");if(!icon)throw new Exception("Missing wuxia app icon");foreach(var target in new[]{UnityEditor.Build.NamedBuildTarget.Unknown,UnityEditor.Build.NamedBuildTarget.Standalone}){var sizes=PlayerSettings.GetIconSizes(target,IconKind.Any);var icons=new Texture2D[Mathf.Max(1,sizes.Length)];for(int i=0;i<icons.Length;i++)icons[i]=icon;PlayerSettings.SetIcons(target,icons,IconKind.Any);Debug.Log("WUXIA_ICON_CONFIGURED "+target.TargetName+" sizes="+icons.Length);}PlayerSettings.bundleVersion="1.7.1-unity";AssetDatabase.SaveAssets();}
  static void Build(BuildTarget target,string path){if(!File.Exists(scene))Setup();ConfigureAppIcon();PlayerSettings.SetScriptingBackend(UnityEditor.Build.NamedBuildTarget.Standalone,ScriptingImplementation.Mono2x);Directory.CreateDirectory(Path.GetDirectoryName(path));var r=BuildPipeline.BuildPlayer(new BuildPlayerOptions{scenes=new[]{scene},locationPathName=path,target=target,options=BuildOptions.None});if(r.summary.result!=BuildResult.Succeeded)throw new Exception("Build failed for "+target+": "+r.summary.result);Directory.CreateDirectory("Documentation/Validation");File.WriteAllText("Documentation/Validation/build-"+target+".txt","Unity "+Application.unityVersion+"\nTarget: "+target+"\nBackend: Mono\nResult: "+r.summary.result+"\nSize: "+r.summary.totalSize+" bytes\nBuilt: "+DateTime.Now.ToString("O"));Debug.Log("WUXIA_BUILD_OK "+target+": "+r.summary.totalSize);}
  [MenuItem("武侠遗境/构建 macOS 离线试玩")]
  public static void BuildMac()=>Build(BuildTarget.StandaloneOSX,"Builds/macOS/武侠遗境.app");
  [MenuItem("武侠遗境/构建 Windows 离线试玩")]
  public static void BuildWindows(){PlayerSettings.SetUseDefaultGraphicsAPIs(BuildTarget.StandaloneWindows64,false);PlayerSettings.SetGraphicsAPIs(BuildTarget.StandaloneWindows64,new[]{UnityEngine.Rendering.GraphicsDeviceType.Direct3D11});Build(BuildTarget.StandaloneWindows64,"Builds/Windows/WuxiaYijing.exe");}
  [MenuItem("武侠遗境/构建 Linux 离线试玩")]
  public static void BuildLinux(){PlayerSettings.SetUseDefaultGraphicsAPIs(BuildTarget.StandaloneLinux64,false);PlayerSettings.SetGraphicsAPIs(BuildTarget.StandaloneLinux64,new[]{UnityEngine.Rendering.GraphicsDeviceType.OpenGLCore});Build(BuildTarget.StandaloneLinux64,"Builds/Linux/WuxiaYijing.x86_64");}
 }
}
